### ISSUE TITLE
StackOverflowError on java.net.SocketInputStream

### ISSUE THREAD

**Issue by visox** [jhy/jsoup#1016]
This is probably a bug of JDK rather then jsoup but is there a solution, workaround ?

```
java.lang.StackOverflowError
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2074)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:854)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)

... lots of repeating
```
i am using the latest jsoup

my system `Debian 9`

java --version
```
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

jsoup code/scala (may or may not be relevant)
```
        val con = Jsoup.connect(url)

        con.headers(headers.asJava)
        con.userAgent(agent)
        con.followRedirects(true)
        con.validateTLSCertificates(false)
        con.ignoreHttpErrors(true)
        con.maxBodySize(1024 * 1024 * 3)
        con.cookies(lastCookies.asJava)
        con.referrer(referrer)
        _setup.map(_.proxy.toProxy).foreach(con.proxy)
        con.timeout(connectionTimeout.toMillis.toInt)

        val r = con.execute()

        lastCookies = r.cookies().asScala.toMap[String, String]

        val parsed = r.parse()
```

**Comment by visox** [comment]
Could it be that redirections are doing this ?
```
val con = Jsoup.connect(url)
...
con.followRedirects(true)
```
?

**Comment by visox** [comment]
After another million of crawled pages i got an another stackoverflow exception this time with a different stack:

```
------------ UNHANDLED EXCEPTION ---------- (Strategy.fromFixedDaemonPool-75)
java.lang.StackOverflowError
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:257)
        at java.base/java.net.SocketOutputStream.<init>(SocketOutputStream.java:58)
        at java.base/java.net.AbstractPlainSocketImpl.getOutputStream(AbstractPlainSocketImpl.java:494)
        at java.base/java.net.Socket$3.run(Socket.java:954)
        at java.base/java.net.Socket$3.run(Socket.java:952)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.Socket.getOutputStream(Socket.java:951)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:476)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
```

**Comment by jhy** [comment]
Have you got a URL where you see this on?

**Comment by visox** [comment]
No actually after some investigation i figured the problem was not enough RAM.

The issue was very random and probably didnt depend on a specific URL/page

**Comment by jhy** [comment]
OK, makes sense. Thanks.
