### ISSUE TITLE
Strange connection exception

### ISSUE THREAD

**Issue by pkk0** [jhy/jsoup#1033]
Hello,
I built version 1.11.3 from official sources (I needed one comit issued after the official version 1.11.2).
Unfortunately for unexplained reasons when connecting in the following way:
```
try {
    Document d = Jsoup.connect("some_url").get();
    (…)    
} catch (Exception e) {
    Debug.send(Log.getStackTraceString(e);
}

```
My android application keeps crashing for a small percentage of devices(Android 6.0, 6.0.1 and 7.0)

Errors:
1. ConstrainableInputStream line 64
org.jsoup.internal.ConstrainableInputStream.read:
> Fatal Exception: org.a.e: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
>        at org.jsoup.parser.CharacterReader.bufferUp(SourceFile:63)
>        at org.jsoup.parser.CharacterReader.current(SourceFile:93)
>        at org.jsoup.parser.TokeniserState$1.read(SourceFile:12)
>        at org.jsoup.parser.Tokeniser.read(SourceFile:45)
>        at org.jsoup.parser.TreeBuilder.runParser(SourceFile:51)
>        at org.jsoup.parser.TreeBuilder.parse(SourceFile:45)
>        at org.jsoup.parser.Parser.parseInput(SourceFile:39)
>        at org.jsoup.helper.DataUtil.parseInputStream(SourceFile:151)
>        at org.jsoup.helper.HttpConnection$Response.parse(SourceFile:837)
>        at org.jsoup.helper.HttpConnection.get(SourceFile:291)
>        my function - Jsoup.connect(...) line
>        at java.lang.Thread.run(Thread.java:818)

> Caused by java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
>        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
>        at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
>        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
>        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
>        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
>        at com.android.okhttp.okio.Okio$2.read(Okio.java:140)
>        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
>        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
>        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:466)
>        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
>        at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:175)
>        at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
>        at org.jsoup.internal.ConstrainableInputStream.read(SourceFile:64)
>        at java.io.InputStreamReader.read(InputStreamReader.java:233)
>        at java.io.BufferedReader.fillBuf(BufferedReader.java:172)
>        at java.io.BufferedReader.read(BufferedReader.java:333)
>        at java.io.Reader.read(Reader.java:141)
>        at org.jsoup.parser.CharacterReader.bufferUp(SourceFile:53)
>        at org.jsoup.parser.CharacterReader.current(SourceFile:93)
>        at org.jsoup.parser.TokeniserState$1.read(SourceFile:12)
>        at org.jsoup.parser.Tokeniser.read(SourceFile:45)
>        at org.jsoup.parser.TreeBuilder.runParser(SourceFile:51)
>        at org.jsoup.parser.TreeBuilder.parse(SourceFile:45)
>        at org.jsoup.parser.Parser.parseInput(SourceFile:39)
>        at org.jsoup.helper.DataUtil.parseInputStream(SourceFile:151)
>        at org.jsoup.helper.HttpConnection$Response.parse(SourceFile:837)
>        at org.jsoup.helper.HttpConnection.get(SourceFile:291)
>        my function - Jsoup.connect(...) line
>        at java.lang.Thread.run(Thread.java:818)

> Caused by android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
>        at libcore.io.Posix.recvfromBytes(Posix.java)
>        at libcore.io.Posix.recvfrom(Posix.java:189)
>        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
>        at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
>        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
>        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
>        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
>        at com.android.okhttp.okio.Okio$2.read(Okio.java:140)
>        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
>        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
>        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:466)
>        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
>        at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:175)
>        at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
>        at org.jsoup.internal.ConstrainableInputStream.read(SourceFile:64)
>        at java.io.InputStreamReader.read(InputStreamReader.java:233)
>        at java.io.BufferedReader.fillBuf(BufferedReader.java:172)
>        at java.io.BufferedReader.read(BufferedReader.java:333)
>        at java.io.Reader.read(Reader.java:141)
>        at org.jsoup.parser.CharacterReader.bufferUp(SourceFile:53)
>        at org.jsoup.parser.CharacterReader.current(SourceFile:93)
>        at org.jsoup.parser.TokeniserState$1.read(SourceFile:12)
>        at org.jsoup.parser.Tokeniser.read(SourceFile:45)
>        at org.jsoup.parser.TreeBuilder.runParser(SourceFile:51)
>        at org.jsoup.parser.TreeBuilder.parse(SourceFile:45)
>        at org.jsoup.parser.Parser.parseInput(SourceFile:39)
>        at org.jsoup.helper.DataUtil.parseInputStream(SourceFile:151)
>        at org.jsoup.helper.HttpConnection$Response.parse(SourceFile:837)
>        at org.jsoup.helper.HttpConnection.get(SourceFile:291)
>        my function - Jsoup.connect(...) line
>        at java.lang.Thread.run(Thread.java:818)

2. ConstrainableInputStream line 58
org.jsoup.internal.ConstrainableInputStream.read:
> Fatal Exception: org.a.e: java.net.SocketTimeoutException: Read timeout
>        at org.jsoup.parser.CharacterReader.bufferUp(SourceFile:63)
>        at org.jsoup.parser.CharacterReader.current(SourceFile:93)
>        at org.jsoup.parser.TokeniserState$1.read(SourceFile:12)
>        at org.jsoup.parser.Tokeniser.read(SourceFile:45)
>        at org.jsoup.parser.TreeBuilder.runParser(SourceFile:51)
>        at org.jsoup.parser.TreeBuilder.parse(SourceFile:45)
>        at org.jsoup.parser.Parser.parseInput(SourceFile:39)
>        at org.jsoup.helper.DataUtil.parseInputStream(SourceFile:151)
>        at org.jsoup.helper.HttpConnection$Response.parse(SourceFile:837)
>        at org.jsoup.helper.HttpConnection.get(SourceFile:291)
>        my function - Jsoup.connect(...) line
>        at java.lang.Thread.run(Thread.java:818)

> Caused by java.net.SocketTimeoutException: Read timeout
>        at org.jsoup.internal.ConstrainableInputStream.read(SourceFile:58)
>        at java.io.InputStreamReader.read(InputStreamReader.java:233)
>        at java.io.BufferedReader.fillBuf(BufferedReader.java:172)
>        at java.io.BufferedReader.read(BufferedReader.java:333)
>        at java.io.Reader.read(Reader.java:141)
>        at org.jsoup.parser.CharacterReader.bufferUp(SourceFile:53)
>        at org.jsoup.parser.CharacterReader.current(SourceFile:93)
>        at org.jsoup.parser.TokeniserState$1.read(SourceFile:12)
>        at org.jsoup.parser.Tokeniser.read(SourceFile:45)
>        at org.jsoup.parser.TreeBuilder.runParser(SourceFile:51)
>        at org.jsoup.parser.TreeBuilder.parse(SourceFile:45)
>        at org.jsoup.parser.Parser.parseInput(SourceFile:39)
>        at org.jsoup.helper.DataUtil.parseInputStream(SourceFile:151)
>        at org.jsoup.helper.HttpConnection$Response.parse(SourceFile:837)
>        at org.jsoup.helper.HttpConnection.get(SourceFile:291)
>        my function - Jsoup.connect(...) line
>        at java.lang.Thread.run(Thread.java:818)

**Comment by pkk0** [comment]
After Jsoup sources research I saw that org.jsoup.parser.CharacterReader.bufferUp(SourceFile:63) could throw UncheckedIOException which is not an Exception implementation. The solution is therefore obvious.
