### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by rohith28** [jhy/jsoup#1045]
-------------------------------------------------------------------------------
Test set: org.jsoup.integration.ConnectTest
-------------------------------------------------------------------------------
Tests run: 23, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 2.014 sec <<< FAILURE!
postFiles(org.jsoup.integration.ConnectTest)  Time elapsed: 0.034 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<439[63]> but was:<439[72]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.jsoup.integration.ConnectTest.postFiles(ConnectTest.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by jhy** [comment]
Hi - can you provide some details please. What's your build environment? How are you initiating the tests? Can you add the XML from Surefire reports?

**Comment by rohith28** [comment]
I am running it on 
OS: Windows 10 
  
I am following the steps shown in building from source 
git clone https://github.com/jhy/jsoup.git
cd jsoup
mvn install

When I ran mvn install then it shown as Build Failure. 

Surefire xml : 

<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="23" failures="1" name="org.jsoup.integration.ConnectTest" time="1.639" errors="0" skipped="5">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="C:\Program Files (x86)\Java\jdk1.8.0_131\jre\bin"/>
    <property name="java.vm.version" value="25.131-b11"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="D:\GitHub\jsoup"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="D:\GitHub\jsoup"/>
    <property name="java.runtime.version" value="1.8.0_131-b11"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\prani\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 10"/>
    <property name="classworlds.conf" value="C:\Program Files\apache-maven-3.5.3\bin\..\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Java\jdk1.8.0_131\bin;C:\ProgramData\Oracle\Java\javapath;C:\iverilog\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\PuTTY\;C:\Program Files\MATLAB\R2017b\bin;C:\gradle-4.3.1\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\apache-maven-3.5.3\bin;D:\GitHub\censusreporter\censusreporter\apps;C:\Users\prani\AppData\Local\Programs\Python\Python36-32\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\prani\AppData\Local\GitHubDesktop\bin;C:\Users\prani\AppData\Roaming\npm;C:\Users\prani\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\gradle-4.3.1\bin;C:\gradle-4.3.1\bin;C:\Users\prani\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.6;C:\Users\prani\AppData\Roaming\Dashlane\5.8.0.17084\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\prani\AppData\Roaming\Dashlane\5.8.0.17084\ucrt;C:\Users\prani\AppData\Local\Yarn\bin;D:\GitHub\censusreporter\censusreporter;D:\GitHub\censusreporter\censusreporter\apps;C:\Program Files\apache-maven-3.5.3\bin;;."/>
    <property name="maven.conf" value="C:\Program Files\apache-maven-3.5.3\bin\../conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="10.0"/>
    <property name="library.jansi.path" value="C:\Program Files\apache-maven-3.5.3\bin\..\lib\jansi-native"/>
    <property name="user.home" value="C:\Users\prani"/>
    <property name="user.timezone" value="America/New_York"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="user.name" value="prani"/>
    <property name="java.class.path" value="C:\Program Files\apache-maven-3.5.3\bin\..\boot\plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="C:\Program Files (x86)\Java\jdk1.8.0_131\jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher install"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_131"/>
    <property name="java.ext.dirs" value="C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_131\jre\classes"/>
    <property name="sun.stderr.encoding" value="cp437"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="C:\Program Files\apache-maven-3.5.3\bin\.."/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.stdout.encoding" value="cp437"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase classname="org.jsoup.integration.ConnectTest" name="multipleParsesOkAfterBufferUp" time="0.342"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="multiCookieSet" time="0.551"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="canInterruptBodyStringRead" time="0.551">
    <skipped/>
  </testcase>
  <testcase classname="org.jsoup.integration.ConnectTest" name="bodyAndBytesAvailableBeforeParse" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="parseParseThrowsValidates" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="totalTimeout" time="0">
    <skipped/>
  </testcase>
  <testcase classname="org.jsoup.integration.ConnectTest" name="fetchURIWithWihtespace" time="0.015"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="infiniteReadSupported" time="0.015">
    <skipped/>
  </testcase>
  <testcase classname="org.jsoup.integration.ConnectTest" name="sendsRequestBodyWithUrlParams" time="0.047"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="fetchURl" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="sendsRequestBody" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="bodyAfterParseThrowsValidationError" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="doesPost" time="0.016"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="supportsDeflate" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="canInterruptDocumentRead" time="0">
    <skipped/>
  </testcase>
  <testcase classname="org.jsoup.integration.ConnectTest" name="sendsRequestBodyJsonWithoutData" time="0.015"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="sendsRequestBodyJsonWithData" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="canConnectToLocalServer" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="doesGet" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="doesPut" time="0.019"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="exceptOnUnsupportedProtocol" time="0"/>
  <testcase classname="org.jsoup.integration.ConnectTest" name="postFiles" time="0.034">
    <failure message="expected:&lt;439[63]&gt; but was:&lt;439[72]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: expected:&lt;439[63]&gt; but was:&lt;439[72]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.jsoup.integration.ConnectTest.postFiles(ConnectTest.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
  </testcase>
  <testcase classname="org.jsoup.integration.ConnectTest" name="slowReadOk" time="0.034">
    <skipped/>
  </testcase>
</testsuite>

**Comment by jhy** [comment]
OK, this is because your git install is converting the \n line endings in the test file to \r\n, so the file size check is wrong. Turns out I'd put a note in the source already:

https://github.com/jhy/jsoup/blob/2c4e79b104c0ff32566ce247617d47c0b39cc2c7/src/test/java/org/jsoup/integration/ConnectTest.java#L301

I will add a .gitattributes to force it so people don't have to configure git on their own.

**Comment by jhy** [comment]
OK, I added them in 47a7f5ab2a22a2ce526f96e0cf9f2c46511c56d9. So you can clear and re-checkout the project and it should work. LMK any issues.

**Comment by rohith28** [comment]
Great !!! It is working now. I able to build successfully.

Thanks @jhy
