### ISSUE TITLE
javax.net.ssl.SSLException: Read error

### ISSUE THREAD

**Issue by eakteam** [jhy/jsoup#1047]
Fatal Exception: org.jsoup.UncheckedIOException: javax.net.ssl.SSLException: Read error: ssl=0x7f5cef6840: I/O error during system call, Software caused connection abort
       at org.jsoup.parser.CharacterReader.bufferUp(CharacterReader.java:60)
       at org.jsoup.parser.CharacterReader.current(CharacterReader.java:85)
       at org.jsoup.parser.TokeniserState.readData(TokeniserState.java:1669)
       at org.jsoup.parser.TokeniserState.access$200(TokeniserState.java:8)
       at org.jsoup.parser.TokeniserState$5.read(TokeniserState.java:71)
       at org.jsoup.parser.Tokeniser.read(Tokeniser.java:45)
       at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:51)
       at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:45)
       at org.jsoup.parser.Parser.parseInput(Parser.java:39)
       at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:151)
       at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:832)
       at org.jsoup.helper.HttpConnection.get(HttpConnection.java:289)
       at java.lang.Thread.run(Thread.java:760)

**Comment by jhy** [comment]
This is the same root cause as #980. Please go ahead and move to 1.11.3.

**Comment by jhy** [comment]
@eos1d3 you can validate the impl in 1.11.3 here - https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/DataUtil.java#L154
