### ISSUE TITLE
INVALID_CHARACTER_ERR when converting Document to W3C (different page)

### ISSUE THREAD

**Issue by dportabella** [jhy/jsoup#1093]
`org.jsoup.nodes.Document doc = Jsoup.parse(new java.io.File("test.html"), null);`
But trying to convert this to a W3C document fails:

```
new W3CDom().fromJsoup(doc);

Exception in thread "main" org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at org.apache.xerces.dom.CoreDocumentImpl.checkQName(Unknown Source)
	at org.apache.xerces.dom.ElementNSImpl.setName(Unknown Source)
	at org.apache.xerces.dom.ElementNSImpl.<init>(Unknown Source)
	at org.apache.xerces.dom.CoreDocumentImpl.createElementNS(Unknown Source)
	at org.jsoup.helper.W3CDom$W3CBuilder.head(W3CDom.java:94)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:45)
	at org.jsoup.helper.W3CDom.convert(W3CDom.java:64)
	at org.jsoup.helper.W3CDom.fromJsoup(W3CDom.java:45)

```

Is there a way to know where is the invalid or illegal XML charachter in the source html file (test.html)?

Can this be fixed?

test.html can be downloaded here: https://www.dropbox.com/s/w3zayut0kryy12s/test.html?dl=0

Note: I am using the latest version of jsoup.
Note: the example on https://github.com/jhy/jsoup/issues/721 works well.

**Comment by jhy** [comment]
@dportabella apologies for the late reply. Do you still have that file or an example? Can you attach it here or on a gist, so it doesn't go away?

**Comment by smatei** [comment]
Hello @jhy,
I found a page that throws this error. I am using 1.13.1

[html.zip](https://github.com/jhy/jsoup/files/4727648/html.zip)

**Comment by jhy** [comment]
Thanks! I've fixed this - now if a tag contains XML illegal names, we insert it as a textnode instead.
