### ISSUE TITLE
ArrayIndexOutOfBoundsException when parsing with some URL

### ISSUE THREAD

**Issue by KeeLi** [jhy/jsoup#1172]
### error
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 11
	at org.jsoup.helper.HttpConnection$Base.looksLikeUtf8(HttpConnection.java:437)
	at org.jsoup.helper.HttpConnection$Base.fixHeaderEncoding(HttpConnection.java:400)
	at org.jsoup.helper.HttpConnection$Base.addHeader(HttpConnection.java:386)
	at org.jsoup.helper.HttpConnection$Response.processResponseHeaders(HttpConnection.java:1075)
	at org.jsoup.helper.HttpConnection$Response.setupFromConnection(HttpConnection.java:1019)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:752)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
```

### code
```
try {
            String url = "https://www.colisprive.com/moncolis/pages/detailColis.aspx?numColis=P4000000037777930";
            Connection connection = Jsoup.connect(url).referrer(url).
                    userAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36")
                    .ignoreContentType(true).timeout(20000);
           
            connection.method(Method.GET);
            return connection.execute().parse();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```

**Comment by jhy** [comment]
Thanks for the report and the deep dive here! Fixed
