### ISSUE TITLE
Unnecessary URL encoding on redirect

### ISSUE THREAD

**Issue by rootext** [jhy/jsoup#1196]
Already encoded URL is encoded second time on redirect.
The following code fails in case of HTTPS redirection on site:
```java
URL url = new URL("http://example.com/name%20with%20spaces");
return HttpConnection.connect(url).ignoreContentType(true).execute().url().openStream();
```
because it requests
https://http://example.com/name%2520with%2520spaces
instead of 
https://http://example.com/name%20with%20spaces

**Comment by jhy** [comment]
Can you provide a full test case? E.g. include the actual URL, so I can replicate. I can't replicate it and there are tests for encoded (and non-encoded) redirects. 

Also, why are you calling openStream() on the URL there after executing it? Execution already makes a HTTP fetch, and then .openStream will fetch it again.

https://github.com/jhy/jsoup/blob/105f7bdcdbfffc879d0737cf857c02b6823b1b73/src/test/java/org/jsoup/integration/UrlConnectTest.java#L541

**Comment by PabloSensei** [comment]
@jhy For example you can use these URLs:
http://www.okbih.ba/pdf/financial_guidelines/C%20-%202013-2016%20Financial%20Report.xlsx
http://cdcontent.books24x7.com/id_16959/financial%20statements.xlsx

**Comment by jhy** [comment]
Sorry, I'm still not getting it. Can you please post a complete code example of where this issue is happening? I wrote a test where I parse a doc with a link to that file and fetch it. 

https://gist.github.com/jhy/18b4e8f6746fffec35dca9cc4cee9b7b

It downloads it fine and gives the same output as a regular browser download (prints 129522).

I traced through Charles Proxy and there's no redirect, either.

**Comment by jhy** [comment]
And, the return from `.url()` is the same as the input string. So I can't find this double escape with the details you've provided.

`System.out.println(con.url().toExternalForm());` gives `http://www.okbih.ba/pdf/financial_guidelines/C%20-%202013-2016%20Financial%20Report.xlsx`

**Comment by rootext** [comment]
@jhy, 
Code from the first comment
```Java
URL url = new URL("http://cdcontent.books24x7.com/id_16959/financial%20statements.xlsx");
InputStream stream = HttpConnection.connect(url).ignoreContentType(true).execute().url().openStream();
```
throws
```
org.jsoup.HttpStatusException: HTTP error fetching URL
. Status=404, URL=https://cdcontent.books24x7.com/id_16959/financial%2520statements.xlsx
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:679)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:676)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:628)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:260)
	at com.datawatch.nserver.dataengine.io.connection.UnsupportedConnectionHandlerTest.shouldThrowExceptionDuringProcessingPrepareReaderProvide1r(UnsupportedConnectionHandlerTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by rootext** [comment]
It isn't reproduced with latest versions. Really ancient version was used in my case. Sorry for disturbing.
