### ISSUE TITLE
Every time: println needs a message

### ISSUE THREAD

**Issue by emdy** [jhy/jsoup#1197]
```
try {
     Document doc = Jsoup.connect("https://www.wikipedia.org/").get();
     Log.i("response", doc.title());
}catch (Exception e){
     Log.i("response", e.getMessage()); //java.lang.NullPointerException: println needs a message
}
```

**Comment by laxika** [comment]
Can you please provide a stacktrace as well?

**Comment by emdy** [comment]
```
03-31 19:24:20.762 23474-23474/com.markody.internetproj E/helper1: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
        at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
        at java.net.InetAddress.getAllByName(InetAddress.java:215)
        at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:746)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
        at com.markody.internetproj.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:6550)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3233)
        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6873)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by jhy** [comment]
This is not a jsoup issue. The Android stacktrace suggests your are making network calls on the main thread. Please Google your stacktrace and look at the Android recipes for asyncthread calls.
