### ISSUE TITLE
Android 6.0.1 java.io.IOException: Mark invalid

### ISSUE THREAD

**Issue by LAVACODE** [jhy/jsoup#1238]
I got a problem on device with Android 6.0.1 API23

Everything works fine on Androids 7+

This is what I get:

/System.err: java.io.IOException: Mark invalid
        at org.jsoup.parser.CharacterReader.rewindToMark(CharacterReader.java:132)
        at org.jsoup.parser.Tokeniser.consumeCharacterReference(Tokeniser.java:182)
        at org.jsoup.parser.TokeniserState$38.read(TokeniserState.java:752)
        at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
        at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:55)
        at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:47)
        at org.jsoup.parser.Parser.parseInput(Parser.java:35)
        at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:169)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:835)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:285)
        at pl.ensomedia.inventscanner.MainActivity$Content.doInBackground(MainActivity.java:98)
        at pl.ensomedia.inventscanner.MainActivity$Content.doInBackground(MainActivity.java:85)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
D/ViewRootImpl: #3 mView = null

**Comment by krystiangorecki** [comment]
Duplicate of #1218

**Comment by LAVACODE** [comment]
Connection.Response execute = Jsoup.connect(urlRossman).execute();
Document document = Jsoup.parse(execute.body());

Solved problem

**Comment by U17A** [comment]
What if a POST request is necessary?

**Comment by jhy** [comment]
@U17A now that it's fixed, a workaround in unnecessary.
