### ISSUE TITLE
Bad html causes ArrayIndexOutOfBoundsException (v1.11.3), UncheckedIOException (v1.12.1)

### ISSUE THREAD

**Issue by HansBrende** [jhy/jsoup#1251]
```java
public void test() {
    byte[] data = new URL("https://github.com/apache/any23/files/3551705/weirdjsoupmin.txt").openStream().readAllBytes();
    Parser.parseFragment(new String(data, StandardCharsets.ISO_8859_1), null, "", ParseErrorList.tracking(1));
}
```

Output (jsoup v1.11.3):
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jsoup.parser.CharacterReader.consume(CharacterReader.java:99)
	at org.jsoup.parser.TokeniserState$34.read(TokeniserState.java:552)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:51)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:126)
	at org.jsoup.parser.Parser.parseFragment(Parser.java:138)

Output (jsoup v1.12.1):
> Exception in thread "main" org.jsoup.UncheckedIOException: java.io.IOException: No buffer left to unconsume
	at org.jsoup.parser.CharacterReader.unconsume(CharacterReader.java:111)
	at org.jsoup.parser.TokeniserState$41.read(TokeniserState.java:877)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:55)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:126)
	at org.jsoup.parser.Parser.parseFragment(Parser.java:140)
Caused by: java.io.IOException: No buffer left to unconsume
	... 7 more

This exception originally occurred when parsing the webpage https://www.streetpadel.com/overgrip-head-pro-grip-dz-negro-p-17233.html but I whittled the html down to a minimal example that reproduces the issue, here: https://github.com/apache/any23/files/3551705/weirdjsoupmin.txt. 

Cf. [ANY23-441](https://github.com/apache/any23/pull/139)

**Comment by HansBrende** [comment]
Interestingly, these errors ONLY occur when I supply a `ParseErrorList.tracking(...)`. If I leave that argument out, jsoup doesn't seem to have a problem with it.

**Comment by HansBrende** [comment]
Addendum: here is a more minimal test case than the one I provided above, that doesn't rely on an external url, and is agnostic to the internal constants set in `CharacterReader`:

```java
@Test
public void testIssue1251() throws Exception {
    StringBuilder str = new StringBuilder("<a href=\"\"ca");
    for (int countSpaces = 0; countSpaces < 100000; countSpaces++) {
        try {
            Parser.htmlParser().setTrackErrors(1).parseInput(str.toString(), "");
        } catch (Exception e) {
            throw new AssertionError("failed at length " + str.length(), e);
        }
        str.insert(countSpaces, ' ');
    }
}
```

prints:

```
java.lang.AssertionError: failed at length 24577
    ...
Caused by: org.jsoup.UncheckedIOException: java.io.IOException: No buffer left to unconsume
	at org.jsoup.parser.CharacterReader.unconsume(CharacterReader.java:112)
	at org.jsoup.parser.TokeniserState$41.read(TokeniserState.java:877)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:55)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:47)
	at org.jsoup.parser.Parser.parseInput(Parser.java:31)
	at org.jsoup.parser.HtmlParserTest.testStuff(HtmlParserTest.java:42)
	... 22 more
Caused by: java.io.IOException: No buffer left to unconsume
	... 29 more
```

**Comment by jhy** [comment]
Thanks, confirmed this was fixed by c2b1fe73129e9c23d93e5393ce8007995c1630dc and added an IT test

**Comment by bypie5** [comment]
Is there a better way to test this issue? This test takes a very long time while computing code coverage. This test case just seems like such an anomaly compared to the other tests in this project.

**Comment by jhy** [comment]
> Is there a better way to test this issue? This test takes a very long time while computing code coverage. This test case just seems like such an anomaly compared to the other tests in this project.

I disabled it by default in 530c5b0fcbef330ea762071144a864e19b1c7595 as there are more specific boundary checks for unconsume now.
