### ISSUE TITLE
Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by MadalinBalint** [jhy/jsoup#1266]
I am getting this error when I'm trying to do a web scraping on this address:

https://ec.europa.eu/growth/tools-databases/cosing/index.cfm?fuseaction=search.details_v2&id=57058

Stack trace:

java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at org.jsoup.internal.ConstrainableInputStream.read(ConstrainableInputStream.java:64)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at java.base/java.io.Reader.read(Reader.java:229)
	at org.jsoup.parser.CharacterReader.bufferUp(CharacterReader.java:58)
	at org.jsoup.parser.CharacterReader.<init>(CharacterReader.java:35)
	at org.jsoup.parser.CharacterReader.<init>(CharacterReader.java:43)
	at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:38)
	at org.jsoup.parser.HtmlTreeBuilder.initialiseParse(HtmlTreeBuilder.java:65)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:46)
	at org.jsoup.parser.Parser.parseInput(Parser.java:35)
	at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:169)
	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:835)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:285)

Using version 1.12.1 (latest).

**Comment by spypunk** [comment]
Same issue with the following URL: http://gutenberg.org/catalog/

Version 1.12.1

**Comment by jhy** [comment]
Thanks - I can repro both of those. Wonder what's going on...

**Comment by jhy** [comment]
I have a feeling this is related to issues near https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4040920 and https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6519463

6519463 says it's fixed in 1.7. But the comment on `Inflater(boolean nowrap)` still says it needs an extra byte, and `ZipFile.fill()` still adds it, but GZIPInputStream does not. So, I think we need to override fill() and do that same trick.

Or, catch the EOF and just go merrily along (which seems a bit dumb).

https://issues.apache.org/jira/browse/HTTPCLIENT-1869 looks like a similar / same issue? Doesn't seem to be resolved.

**Comment by jhy** [comment]
I am going to close this out - I haven't seen other repros of it, and I don't see those URLs replicating the issue now. It may have been server-side, or an issue in an old Java version that's worked its way out of use. The aforementioned HttpClient issue also closed it out as no evidence of a client bug.

If you see further repros that other browsers are handling better, please re-open and add notes.
