### ISSUE TITLE
Document.select(String) does not handle white spaces correctly

### ISSUE THREAD

**Issue by tetheber** [jhy/jsoup#1290]
Version 1.12.1

When a css class name contains white spaces (at the end), the following exception is thrown.
I am not sure whether white spaces at the end of a class name represent valid css syntax, however I have seen it in a real live case.

Stack Trace and sample files attached.

[bug_report.zip](https://github.com/jhy/jsoup/files/4006474/bug_report.zip)
 

Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: Could not parse query '': unexpected token at ''
	at org.jsoup.select.QueryParser.findElements(QueryParser.java:206)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:59)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:42)
	at org.jsoup.select.QueryParser.combinator(QueryParser.java:87)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:69)
	at org.jsoup.select.QueryParser.parse(QueryParser.java:42)
	at org.jsoup.select.Selector.select(Selector.java:91)
	at org.jsoup.nodes.Element.select(Element.java:372)
	at JsoupBug.main(JsoupBug.java:14)

**Comment by jhy** [comment]
Hi, thanks for the report. This is not a bug. HTML classes do not contain spaces - spaces in a class attribute are separators. The exception is thrown because the query is invalid as unquoted spaces in selectors are also separators.

When parsed, the DOM for this element has a classList of `["main_class"]`. So the selector `.main_class` will find it.

See e.g. https://try.jsoup.org/~5Q93rNGMBeid0ou6uL97I72CcoU

**Comment by tetheber** [comment]
Ok, thank's for your explanation.
