### ISSUE TITLE
Sometimes throw java.io.IOException: Mark invalid

### ISSUE THREAD

**Issue by kudlav** [jhy/jsoup#1304]
Version: 1.12.1

When I'm trying to parse following website, sometimes Mark invalid appears. And when it appears it can be thrown for example five times in a row. I am unable to grab html when the exception is thrown and post it here.

This website: [http://www.kam.vutbr.cz/?p=otdo](http://www.kam.vutbr.cz/?p=otdo)
It is problem of every Jsoup usage in my app, so even for these websites:
http://www.kam.vutbr.cz/?p=menu&provoz=18
http://www.kam.vutbr.cz/?p=oper

```
java.io.IOException: Mark invalid
	at org.jsoup.parser.CharacterReader.rewindToMark(CharacterReader.java:132)
	at org.jsoup.parser.Tokeniser.consumeCharacterReference(Tokeniser.java:182)
	at org.jsoup.parser.TokeniserState.readCharRef(TokeniserState.java:1698)
	at org.jsoup.parser.TokeniserState.access$100(TokeniserState.java:8)
	at org.jsoup.parser.TokeniserState$2.read(TokeniserState.java:36)
	at org.jsoup.parser.Tokeniser.read(Tokeniser.java:57)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:55)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:47)
	at org.jsoup.parser.Parser.parseInput(Parser.java:35)
	at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:169)
	at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:835)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:285)
	at com.kudlav.kam.MainActivity$DownloadOpeningHours.doInBackground(MainActivity.kt:110)
	at com.kudlav.kam.MainActivity$DownloadOpeningHours.doInBackground(MainActivity.kt:99)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

Here is simplified Jsoup code (Kotlin):
```
Jsoup.connect("http://www.kam.vutbr.cz/?p=otdo").get().run {
                    val tr = select("#sa2 > .ntab > tbody > tr")
                    for (i: Int in 1 until tr.size) {
                        val td = tr[i].getElementsByTag("td")
                        val id = td[0].getElementsByTag("a")
                        val state = td[1].text()
                    }
                }
```
This bug also affects .post() method.

Similar:
https://github.com/jhy/jsoup/issues/1238
https://github.com/jhy/jsoup/issues/1218
https://github.com/jhy/jsoup/issues/992

**Comment by jhy** [comment]
Hi - I verified that this is fixed in #1218 (by reverting that fix, verifying that I got the error around one of 10 attempts, and then verifying it is not reproducible in 1 of 100).
