### ISSUE TITLE
Updating from 1.8.3 to 1.12.1 breaks

### ISSUE THREAD

**Issue by SElab2019** [jhy/jsoup#1310]
When I try to upgrade Jsoup from 1.8.3 to the version after 1.11.1. The following code breaks.
```
public class TestJsoup {
	
	@Test
	public void testSanitizeBasicHTML() {
	
        String unsafeStr = "the <a href=\"http://dataverse.org\" target=\"_blank\">Dataverse project</a> in a new window";
        String safeStr = "the \n<a href=\"http://dataverse.org\" rel=\"nofollow\" target=\"_blank\">Dataverse project</a> in a new window";
        String sanitized = sanitizeBasicHTML(unsafeStr);
        assertTrue(safeStr.equals(sanitized));
        
	}
	
    public static String sanitizeBasicHTML(String unsafe){

        Whitelist wl = Whitelist.basicWithImages().addTags( "h1", "h2", "h3", "kbd", "hr", "s", "del","map","area").addAttributes("img", "usemap")
                .addAttributes("map", "name").addAttributes("area", "shape","coords","href","title","alt")
                .addEnforcedAttribute("a", "target", "_blank");
        return Jsoup.clean(unsafe, wl);
        
    }
}
```

The test should pass, but it failed with the error:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at TestJsoup.testSanitizeBasicHTML(TestJsoup.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by jhy** [comment]
Hi, the parts that are different here are that the spurious newlines are removed, and the order of the attributes changed. The specific format of the HTML is subject to change between versions (see the CHANGES file) and is not part of the API contract.

The actual current (in HEAD) output is:
`the <a href="http://dataverse.org" target="_blank" rel="nofollow">Dataverse project</a> in a new window`

My suggestion would be that you use the `assertEquals(want, got)` format vs a `want.equals(got)` style. That way, JUnit can tell you what the difference was and it makes it easier to debug / update.

Also, you might want to add `rel=noopener` if you are adding `target=_blank` to avoid the opened site being able to take over the linking site. See https://developers.google.com/web/tools/lighthouse/audits/noopener
