### ISSUE TITLE
Updating from 1.9.2 to 1.12.1 breaks due to the QueryParser

### ISSUE THREAD

**Issue by SElab2019** [jhy/jsoup#1311]
When I try to upgrade Jsoup from 1.9.2 to the version after 1.11.1. The following code breaks due to the change of QueryParser.
```
public class TestJsoup {
	
    @Test
    public void testParser() {
    	
        String html = readAllText("TestAttributesTest.html");
        Document doc = Jsoup.parse(html);
        Element categoryView = doc.select("#slide-out").first().select("a[view=category-view']").first();
        Assert.assertNotNull(categoryView);
    	
    }

    public static String readAllText(String filePath) {
        File file = new File(filePath);
        
        if (file.exists()) {
            byte[] data;
            
            try (FileInputStream fis = new FileInputStream(file)) {
                data = new byte[(int)file.length()];
                fis.read(data);
                
                return new String(data, "UTF-8");
            } 
            catch (IOException e) {
            	System.out.println(e);
            }
        }
        
        return null;
    }
}
```
The html file are shown below:
```

<!DOCTYPE html>
<html>


<head>
	<meta charset='utf-8' /> 
	<meta name='description' content='' />
	<meta name='robots' content='noodp, noydir' />
	<meta name='viewport' content='width=device-width, initial-scale=1' />
	<meta id="timeStampFormat" name="timeStampFormat" content='MMM d, yyyy hh:mm:ss a'/>
	
	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css' />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

		<link href='https://cdn.rawgit.com/anshooarora/extentreports-java/b4a58fcfd1e137bd9287244035a7c80d3d73b3af/dist/css/extent.css' type='text/css' rel='stylesheet' />
	
	<title>ExtentReports</title>

	<style type='text/css'>
	</style>
</head>

	<body class='extent standard default hide-overflow '>
		<div id='theme-selector' alt='Click to toggle theme. To enable by default, use theme configuration.' title='Click to toggle theme. To enable by default, use theme configuration.'>
			<span><i class='material-icons'>desktop_windows</i></span>
		</div>

<nav>
	<div class="nav-wrapper">
		<a href="#!" class="brand-logo blue darken-3">Extent</a>

		<!-- slideout menu -->
		<ul id='slide-out' class='side-nav fixed hide-on-med-and-down'>
			<li class='waves-effect active'><a href='#!' view='test-view' onclick="configureView(0);chartsView('test');"><i class='material-icons'>dashboard</i></a></li>
						<li class='waves-effect'><a href='#!' view='category-view' onclick="configureView(1)"><i class='material-icons'>label_outline</i></a></li>
				<li class='waves-effect'><a href='#!' view='author-view' onclick="configureView(3)"><i class='material-icons'>person</i></a></li>
			<li class='waves-effect'><a href='#!' onclick="configureView(-1);chartsView('dashboard');" view='dashboard-view'><i class='material-icons'>track_changes</i></i></a></li>
		</ul>

		<!-- report name -->
		<span class='report-name'>ExtentReports</span>
		
		<!-- report headline -->
		<span class='report-headline'></span>

		<!-- nav-right -->
		<ul id='nav-mobile' class='right hide-on-med-and-down nav-right'>
			<li>
                <a href='#!'>
                    <span class='label suite-start-time blue darken-3'>Jan 31, 2020 10:49:44 AM</span>
				</a>
			</li>
			<li>
                <a href='#!'>
                    <span class='label blue darken-3'>3.1.5</span>
				</a>
			</li>
		</ul>
	</div>
</nav>

		<!-- container -->
		<div class='container'>

<div id='test-view' class='view'>
				
	<section id='controls'>
		<div class='controls grey lighten-4'>
			<!-- test toggle -->
			<div class='chip transparent'>
				<a class='dropdown-button tests-toggle' data-activates='tests-toggle' data-constrainwidth='true' data-beloworigin='true' data-hover='true' href='#'>
					<i class='material-icons'>warning</i> Status
				</a>
				<ul id='tests-toggle' class='dropdown-content'>
											<li status='pass'><a href='#!'>Pass <i class='material-icons green-text'>check_circle</i></a></li>
					<li class='divider'></li>
					<li status='clear' clear='true'><a href='#!'>Clear Filters <i class='material-icons'>clear</i></a></li>
				</ul>
			</div>
			<!-- test toggle -->

			<!-- category toggle -->
			<div class='chip transparent'>
				<a class='dropdown-button category-toggle' data-activates='category-toggle' data-constrainwidth='false' data-beloworigin='true' data-hover='true' href='#'>
					<i class='material-icons'>local_offer</i> Category
				</a>
				<ul id='category-toggle' class='dropdown-content'>
					<li><a href='#'>extent</a></li>
					<li><a href='#'>git</a></li>
					<li><a href='#'>tests</a></li>
					<li><a href='#'>heroku</a></li>
					<li class='divider'></li>
					<li class='clear'><a href='#!' clear='true'>Clear Filters</a></li>
				</ul>
			</div>
			<!-- category toggle -->

			<!-- clear filters -->
			<div class='chip transparent hide'>
				<a class='' id='clear-filters' alt='Clear Filters' title='Clear Filters'>
					<i class='material-icons'>close</i> Clear
				</a>
			</div>
			<!-- clear filters -->

			<!-- enable dashboard -->
			<div id='toggle-test-view-charts' class='chip transparent'>
				<a class='pink-text' id='enable-dashboard' alt='Enable Dashboard' title='Enable Dashboard'>
					<i class='material-icons'>track_changes</i> Dashboard
				</a>
			</div>
			<!-- enable dashboard -->

			<!-- search -->
			<div class='chip transparent' alt='Search Tests' title='Search Tests'>
				<a href="#" class='search-div'>
					<i class='material-icons'>search</i> Search
				</a>

				<div class='input-field left hide'>
					<input id='search-tests' type='text' class='validate browser-default' placeholder='Search Tests...'>
				</div>
				
			</div>
			<!-- search -->
		</div>
	</section>


<div id='test-view-charts' class='subview-full'>
	<div id='charts-row' class='row nm-v nm-h'>
		<div class='col s12 m6 l6 np-h'>
			<div class='card-panel nm-v'>
				<div class='left panel-name'>Tests</div>
				<div class='chart-box'>
					<canvas id='parent-analysis' width='100' height='80'></canvas>
				</div>
				<div class='block text-small'>
					<span class='tooltipped' data-position='top' data-tooltip='100%'><span class='strong'>4</span> test(s) passed</span>
				</div>
				<div class='block text-small'>
					<span class='strong tooltipped' data-position='top' data-tooltip='0%'>0</span> test(s) failed, <span class='strong tooltipped' data-position='top' data-tooltip='0%'>0</span> others
				</div>
			</div>
		</div>
		
		<div class='col s12 m6 l6 np-h'>
			<div class='card-panel nm-v'>
				<div class='left panel-name'>Steps</div>
				<div class='chart-box'>
					<canvas id='child-analysis' width='100' height='80'></canvas>
				</div>
				<div class='block text-small'>
					<span class='tooltipped' data-position='top' data-tooltip='100%'><span class='strong'>4</span> step(s) passed</span>
				</div>
				<div class='block text-small'>
					<span class='strong tooltipped' data-position='top' data-tooltip='0%'>0</span> step(s) failed, <span class='strong tooltipped' data-position='top' data-tooltip='0%'>0</span> others
				</div>
			</div>
		</div>
		
	</div>
</div>

	<div class='subview-left left'>
		
		<div class='view-summary'>
			<h5>Tests</h5>
			<ul id='test-collection' class='test-collection'>
				
				
				<li class='test displayed active  pass' status='pass' bdd='false' test-id='318'>
					<div class='test-heading'>
						<span class='test-name'>verifyIfTestHasAddedAuthor</span>
						<span class='test-time'>Jan 31, 2020 10:49:44 AM</span>
						<span class='test-status right pass'>pass</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label end-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+0ms</span>
</div>
	<div class='test-attributes'>
			<div class='author-list'>
				<span class='author label white-text'>anshoo</span>
			</div>
	</div>
	<div class='test-steps'>
		<table class='bordered table-results'>
			<thead>
				<tr>
					<th>Status</th>
					<th>Timestamp</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<tr class='log' status='pass'>
					<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
					<td class='timestamp'>10:49:44 AM</td>
					<td class='step-details'>pass</td>
				</tr>
			</tbody>
		</table>
	</div>
					</div>
				</li>
				
				
				<li class='test displayed active  pass' status='pass' bdd='false' test-id='320'>
					<div class='test-heading'>
						<span class='test-name'>verifyIfTestHasAddedAuthors</span>
						<span class='test-time'>Jan 31, 2020 10:49:44 AM</span>
						<span class='test-status right pass'>pass</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label end-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+1ms</span>
</div>
	<div class='test-attributes'>
			<div class='author-list'>
				<span class='author label white-text'>anshoo</span>
				<span class='author label white-text'>viren</span>
				<span class='author label white-text'>maxi</span>
				<span class='author label white-text'>vimal</span>
			</div>
	</div>
	<div class='test-steps'>
		<table class='bordered table-results'>
			<thead>
				<tr>
					<th>Status</th>
					<th>Timestamp</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<tr class='log' status='pass'>
					<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
					<td class='timestamp'>10:49:44 AM</td>
					<td class='step-details'>pass</td>
				</tr>
			</tbody>
		</table>
	</div>
					</div>
				</li>
				
				
				<li class='test displayed active  pass' status='pass' bdd='false' test-id='322'>
					<div class='test-heading'>
						<span class='test-name'>verifyIfTestHasAddedCategories</span>
						<span class='test-time'>Jan 31, 2020 10:49:44 AM</span>
						<span class='test-status right pass'>pass</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label end-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+0ms</span>
</div>
	<div class='test-attributes'>
			<div class='category-list'>
				<span class='category label white-text'>extent</span>
				<span class='category label white-text'>git</span>
				<span class='category label white-text'>tests</span>
				<span class='category label white-text'>heroku</span>
			</div>
	</div>
	<div class='test-steps'>
		<table class='bordered table-results'>
			<thead>
				<tr>
					<th>Status</th>
					<th>Timestamp</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<tr class='log' status='pass'>
					<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
					<td class='timestamp'>10:49:44 AM</td>
					<td class='step-details'>pass</td>
				</tr>
			</tbody>
		</table>
	</div>
					</div>
				</li>
				
				
				<li class='test displayed active  pass' status='pass' bdd='false' test-id='324'>
					<div class='test-heading'>
						<span class='test-name'>verifyIfTestHasAddedCategory</span>
						<span class='test-time'>Jan 31, 2020 10:49:44 AM</span>
						<span class='test-status right pass'>pass</span>
					</div>
					<div class='test-content hide'>
<div class='test-time-info'>
	<span class='label start-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label end-time'>Jan 31, 2020 10:49:44 AM</span>
	<span class='label time-taken grey lighten-1 white-text'>0h 0m 0s+0ms</span>
</div>
	<div class='test-attributes'>
			<div class='category-list'>
				<span class='category label white-text'>extent</span>
			</div>
	</div>
	<div class='test-steps'>
		<table class='bordered table-results'>
			<thead>
				<tr>
					<th>Status</th>
					<th>Timestamp</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<tr class='log' status='pass'>
					<td class='status pass' title='pass' alt='pass'><i class='material-icons'>check_circle</i></td>
					<td class='timestamp'>10:49:44 AM</td>
					<td class='step-details'>pass</td>
				</tr>
			</tbody>
		</table>
	</div>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<!-- subview left -->

	<div class='subview-right left'>
		<div class='view-summary'>
			<h5 class='test-name'></h5>

			<div id='step-filters' class="right">
				<span class="blue-text" status="info" alt="info" title="info"><i class="material-icons">info_outline</i></span>
				<span class="green-text" status="pass" alt="pass" title="pass"><i class="material-icons">check_circle</i></span>
				<span class="red-text" status="fail" alt="fail" title="fail"><i class="material-icons">cancel</i></span>
				<span class="red-text text-darken-4" status="fatal" alt="fatal" title="fatal"><i class="material-icons">cancel</i></span>
				<span class="pink-text text-lighten-1" status="error" alt="error" title="error"><i class="material-icons">error</i></span>
				<span class="orange-text" alt="warning" status="warning" title="warning"><i class="material-icons">warning</i></span>
				<span class="teal-text" status="skip" alt="skip" title="skip"><i class="material-icons">redo</i></span>
				<span status="clear" alt="Clear filters" title="Clear filters"><i class="material-icons">clear</i></span>
			</div>
		</div>
	</div>
	<!-- subview right -->

</div>
<!-- test view -->
<div id='category-view' class='view hide'>

	<section id='controls'>
		<div class='controls grey lighten-4'>
			<!-- search -->
			<div class='chip transparent' alt='Search Tests' title='Search Tests'>
				<a href="#" class='search-div'>
					<i class='material-icons'>search</i> Search
				</a>
				
				<div class='input-field left hide'>
					<input id='search-tests' type='text' class='validate browser-default' placeholder='Search Tests...'>
				</div>
				
			</div>
			<!-- search -->
		</div>
	</section>

	<div class='subview-left left'>
		
		<div class='view-summary'>
			<h5>Categories</h3>
			<ul id='category-collection' class='category-collection'>
				
				<li class='category displayed active'>
					<div class='category-heading'>
						<span class='category-name'>extent</span>
						<span class='category-status right'>
							<span class='label pass'>2</span>
						</span>
					</div>
					<div class='category-content hide'>
						<div class='category-status-counts'>
							<span class='label green accent-4 white-text'>Passed: 2</span>
							
							
						</div>
					
						<div class='category-tests'>
							<table class='bordered table-results'>
								<thead>
									<tr>
										<th>Timestamp</th>
										<th>TestName</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Jan 31, 2020 10:49:44 AM</td>
										<td class='linked' test-id='322'>verifyIfTestHasAddedCategories</td>
										<td><span class='test-status pass'>pass</span></td>
									</tr>
									<tr>
										<td>Jan 31, 2020 10:49:44 AM</td>
										<td class='linked' test-id='324'>verifyIfTestHasAddedCategory</td>
										<td><span class='test-status pass'>pass</span></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</li>
				<li class='category displayed active'>
					<div class='category-heading'>
						<span class='category-name'>git</span>
						<span class='category-status right'>
							<span class='label pass'>1</span>
						</span>
					</div>
					<div class='category-content hide'>
						<div class='category-status-counts'>
							<span class='label green accent-4 white-text'>Passed: 1</span>
							
							
						</div>
					
						<div class='category-tests'>
							<table class='bordered table-results'>
								<thead>
									<tr>
										<th>Timestamp</th>
										<th>TestName</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Jan 31, 2020 10:49:44 AM</td>
										<td class='linked' test-id='322'>verifyIfTestHasAddedCategories</td>
										<td><span class='test-status pass'>pass</span></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</li>
				<li class='category displayed active'>
					<div class='category-heading'>
						<span class='category-name'>tests</span>
						<span class='category-status right'>
							<span class='label pass'>1</span>
						</span>
					</div>
					<div class='category-content hide'>
						<div class='category-status-counts'>
							<span class='label green accent-4 white-text'>Passed: 1</span>
							
							
						</div>
					
						<div class='category-tests'>
							<table class='bordered table-results'>
								<thead>
									<tr>
										<th>Timestamp</th>
										<th>TestName</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Jan 31, 2020 10:49:44 AM</td>
										<td class='linked' test-id='322'>verifyIfTestHasAddedCategories</td>
										<td><span class='test-status pass'>pass</span></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</li>
				<li class='category displayed active'>
					<div class='category-heading'>
						<span class='category-name'>heroku</span>
						<span class='category-status right'>
							<span class='label pass'>1</span>
						</span>
					</div>
					<div class='category-content hide'>
						<div class='category-status-counts'>
							<span class='label green accent-4 white-text'>Passed: 1</span>
							
							
						</div>
					
						<div class='category-tests'>
							<table class='bordered table-results'>
								<thead>
									<tr>
										<th>Timestamp</th>
										<th>TestName</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Jan 31, 2020 10:49:44 AM</td>
										<td class='linked' test-id='322'>verifyIfTestHasAddedCategories</td>
										<td><span class='test-status pass'>pass</span></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</li>

			</ul>
		</div>
	</div>

	<div class='subview-right left'>
		<div class='view-summary'>
			<h5 class='category-name'></h5>
		</div>
	</div>
</div>
<!-- category view -->
<div id='author-view' class='view hide'>
    <section id='controls'>
        <div class='controls grey lighten-4'>
            <!-- search -->
            <div class='chip transparent' alt='Search Authors' title='Search Authors'>
                <a href="#" class='search-div'>
                    <i class='material-icons'>search</i> Search
                </a>

                <div class='input-field left hide'>
                    <input id='search-tests' type='text' class='validate browser-default' placeholder='Search Authors...'>
                </div>

            </div>
            <!-- search -->
        </div>
    </section>

    <div class='subview-left left'>

        <div class='view-summary'>
            <h5>Authors</h5>
                <ul id='author-collection' class='author-collection'>

                        <li class='author displayed active'>
                            <div class='author-heading'>
                                <span class='author-name'>anshoo</span>
                                <span class='author-status right'>
                                        <span class='label pass'>2</span>
						        </span>
                            </div>
                            <div class='author-content hide'>
                                <div class='author-status-counts'>
                                    <span class='label green accent-4 white-text'>Passed: 2</span>
                                    
                                    
                                </div>

                                <div class='author-tests'>
                                    <table class='bordered table-results'>
                                        <thead>
                                        <tr>
                                            <th>Timestamp</th>
                                            <th>TestName</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Jan 31, 2020 10:49:44 AM</td>
                                                <td class='linked' test-id='318'>verifyIfTestHasAddedAuthor</td>
                                                <td><span class='test-status pass'>pass</span></td>
                                            </tr>
                                            <tr>
                                                <td>Jan 31, 2020 10:49:44 AM</td>
                                                <td class='linked' test-id='320'>verifyIfTestHasAddedAuthors</td>
                                                <td><span class='test-status pass'>pass</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </li>
                        <li class='author displayed active'>
                            <div class='author-heading'>
                                <span class='author-name'>viren</span>
                                <span class='author-status right'>
                                        <span class='label pass'>1</span>
						        </span>
                            </div>
                            <div class='author-content hide'>
                                <div class='author-status-counts'>
                                    <span class='label green accent-4 white-text'>Passed: 1</span>
                                    
                                    
                                </div>

                                <div class='author-tests'>
                                    <table class='bordered table-results'>
                                        <thead>
                                        <tr>
                                            <th>Timestamp</th>
                                            <th>TestName</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Jan 31, 2020 10:49:44 AM</td>
                                                <td class='linked' test-id='320'>verifyIfTestHasAddedAuthors</td>
                                                <td><span class='test-status pass'>pass</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </li>
                        <li class='author displayed active'>
                            <div class='author-heading'>
                                <span class='author-name'>maxi</span>
                                <span class='author-status right'>
                                        <span class='label pass'>1</span>
						        </span>
                            </div>
                            <div class='author-content hide'>
                                <div class='author-status-counts'>
                                    <span class='label green accent-4 white-text'>Passed: 1</span>
                                    
                                    
                                </div>

                                <div class='author-tests'>
                                    <table class='bordered table-results'>
                                        <thead>
                                        <tr>
                                            <th>Timestamp</th>
                                            <th>TestName</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Jan 31, 2020 10:49:44 AM</td>
                                                <td class='linked' test-id='320'>verifyIfTestHasAddedAuthors</td>
                                                <td><span class='test-status pass'>pass</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </li>
                        <li class='author displayed active'>
                            <div class='author-heading'>
                                <span class='author-name'>vimal</span>
                                <span class='author-status right'>
                                        <span class='label pass'>1</span>
						        </span>
                            </div>
                            <div class='author-content hide'>
                                <div class='author-status-counts'>
                                    <span class='label green accent-4 white-text'>Passed: 1</span>
                                    
                                    
                                </div>

                                <div class='author-tests'>
                                    <table class='bordered table-results'>
                                        <thead>
                                        <tr>
                                            <th>Timestamp</th>
                                            <th>TestName</th>
                                            <th>Status</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Jan 31, 2020 10:49:44 AM</td>
                                                <td class='linked' test-id='320'>verifyIfTestHasAddedAuthors</td>
                                                <td><span class='test-status pass'>pass</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </li>

                </ul>
        </div>
    </div>

    <div class='subview-right left'>
        <div class='view-summary'>
            <h5 class='author-name'></h5>
        </div>
    </div>
</div>
<!-- exception view -->
<div id='dashboard-view' class='view hide'>
	<div class='card-panel transparent np-v'>
		<h5>Dashboard</h5>

		<div class='row'>
			<div class='col s2'>
				<div class='card-panel r'>
					Tests
					<div class='panel-lead'>4</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Steps
					<div class='panel-lead'>4</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Start
					<div class='panel-lead'>Jan 31, 2020 10:49:44 AM</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
			 		End
			 		<div class='panel-lead'>Jan 31, 2020 10:49:44 AM</div>
				</div>
			</div>
			<div class='col s2'>
				<div class='card-panel r'>
					Time Taken
					<div class='panel-lead'>0h 0m 0s+4ms</div>
				</div>
			</div>
			<div class='col s6'>
				<div class='card-panel dashboard-categories'>
					<span class='right label cyan white-text'>Categories</span><p>&nbsp;</p>
					
					<table>
						<tr>
							<th>Name</th>
							<th>Passed</th>
							<th>Failed</th>
							<th>Others</th>
							<th>Passed %</th>
						</tr>
						<tr>
							<td>extent</td>
							<td>2</td>
							<td>0</td>
							<td>0</td>
							<td>
									100%
							</td>
						</tr>
						<tr>
							<td>git</td>
							<td>1</td>
							<td>0</td>
							<td>0</td>
							<td>
									100%
							</td>
						</tr>
						<tr>
							<td>tests</td>
							<td>1</td>
							<td>0</td>
							<td>0</td>
							<td>
									100%
							</td>
						</tr>
						<tr>
							<td>heroku</td>
							<td>1</td>
							<td>0</td>
							<td>0</td>
							<td>
									100%
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- dashboard view -->
<!-- testrunner-logs view -->
		</div>
		<!-- container -->

		<script>
			var statusGroup = {
				passParent: 4,
				failParent: 0,
				fatalParent: 0,
				errorParent: 0,
				warningParent: 0,
				skipParent: 0,
				exceptionsParent: 0,
				
				passChild: 4,
				failChild: 0,
				fatalChild: 0,
				errorChild: 0,
				warningChild: 0,
				skipChild: 0,
				infoChild: 0,
				exceptionsChild: 0,
				
				passGrandChild: 0,
				failGrandChild: 0,
				fatalGrandChild: 0,
				errorGrandChild: 0,
				warningGrandChild: 0,
				skipGrandChild: 0,
				infoGrandChild: 0,
				exceptionsGrandChild: 0,
			};
		</script>
		
			<script src='https://cdn.rawgit.com/anshooarora/extentreports-java/fca20fb7653aade98810546ab96a2a4360e3e712/dist/js/extent.js' type='text/javascript'></script>
		
		
 		<script type='text/javascript'>
 		</script>
	</body>
	
</html>
```

The test failed with error:
```
testParser(TestJsoup)  Time elapsed: 0.137 sec  <<< ERROR!
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'view=category-view'
	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.select(Selector.java:90)
	at org.jsoup.nodes.Element.select(Element.java:363)
	at TestJsoup.testParser(TestJsoup.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by jhy** [comment]
Yes, the balanced quote validation was improved. Your selector has an error:

`a[view=category-view']`

Should be `a[view='category-view']` or `a[view=category-view]`

**Comment by SElab2019** [comment]
Hi @jhy , thanks for your help. Yes, I could change my selector. BTW, do you think this is a breaking change?

**Comment by jhy** [comment]
Well not really, or I wouldn't have close the bug ;) The validation got a bit stricter, and we did cover it in the change file. Not ideal I know, but manageable I think.
