### ISSUE TITLE
Some HTML input causes NullPointerException in HtmlTreeBuilderState

### ISSUE THREAD

**Issue by sfzhi** [jhy/jsoup#1404]
Running the following: `Jsoup.parseBodyFragment("<isindex>");` results in:
```
java.lang.NullPointerException
	at org.jsoup.parser.HtmlTreeBuilderState$7.inBodyStartTag(HtmlTreeBuilderState.java:454)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:282)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:136)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:66)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:126)
	at org.jsoup.parser.Parser.parseFragment(Parser.java:122)
	at org.jsoup.parser.Parser.parseBodyFragment(Parser.java:166)
	at org.jsoup.Jsoup.parseBodyFragment(Jsoup.java:160)
```
The problem appears to be caused by an attempt to call a method on `startTag.attributes`, which is `null`.
A similar error occurs when running: `Jsoup.parseBodyFragment("<table><input></table>");`.

The issue is discovered in Jsoup 1.13.1. I haven't tested it in the master branch, but looking at the code, it still exists.

**Comment by jhy** [comment]
Thanks for raising the issue, and for the very easy to replicate steps!
