### ISSUE TITLE
find elements using :lang(...) pseudo-class selector throws exception

### ISSUE THREAD

**Issue by dawud-tan** [jhy/jsoup#1447]
I'm trying to find elements using a ```:lang(...)``` pseudo-class selector syntax, but my program throws an exception, maybe the selector has not been supported in jsoup?

```shell
Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: Could not parse query ':lang(jv-Java-ID)': unexpected token at ':lang(jv-Java-ID)'
        at org.jsoup.select.QueryParser.findElements(QueryParser.java:209)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:62)
        at org.jsoup.select.QueryParser.parse(QueryParser.java:45)
        at org.jsoup.select.Selector.select(Selector.java:92)
        at org.jsoup.nodes.Element.select(Element.java:396)
        at CariKarakterTerpakai$DaftarKarakter.<init>(CariKarakterTerpakai.java:67)
        at CariKarakterTerpakai.main(CariKarakterTerpakai.java:25)
```

**Comment by QAQGaeBolg** [comment]
I along with my group will be fixing this issue in this semester.

**Comment by JeffXiesk** [comment]
Maybe :lang() is not support in Jsoup, because it is not included in the [cookbook](https://jsoup.org/apidocs/org/jsoup/select/Selector.html).

**Comment by jhy** [comment]
> I along with my group will be fixing this issue in this semester.

@QAQGaeBolg : I am reaching out to you here because you have no contact information in your profile. Sorry, I don't know who you or your group are, and the commits you've been sending are not production ready. I am I am not in the place to do class tutoring for you if that is your expectation. 

Please stop commenting on issues in a way that is appearing to either be officially confirming a bug or are assigning the issue to yourself and perhaps making others hesitant to contribute.

I welcome production ready commits or those approaching it, but you and your group (who, specifically?) have not been making those, and so far it's just been clutter.

On this issue: I would just recommend selecting off the attribute value vs using the pseudo-selector. It's not currently supported and I haven't seen much demand to add it. I'm not against the feature if there's a good quality PR, though.
