### ISSUE TITLE
android SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by sundy-zhang** [jhy/jsoup#1493]
In Android, some requests will report the following error。

W/System.err: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:216)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1151)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:982)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:736)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)

**Comment by jhy** [comment]
(Closing this out - please re-open if there is a specific test case and a comparison implementation on the same platform that doesn't time out)
