### ISSUE TITLE
[34251] jsoup:HtmlFuzzer: Timeout in HtmlFuzzer

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1544]
Labels: Restrict-View-Commit ClusterFuzz Reproducible Engine-libfuzzer OS-Linux Reported-2021-05-13 Proj-jsoup
Type: Bug

New issue 34251 by ClusterFuzz-External: jsoup:HtmlFuzzer: Timeout in HtmlFuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34251

Detailed Report: https://oss-fuzz.com/testcase?key=6193285828837376

Project: jsoup
Fuzzing Engine: libFuzzer
Fuzz Target: HtmlFuzzer
Job Type: libfuzzer_asan_jsoup
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address: 
Crash State:
  HtmlFuzzer
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_jsoup&revision=202105130607

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6193285828837376

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

**Comment by krystiangorecki** [comment]
This one results in: 
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.jsoup.nodes.Node.indent(Node.java:639)
	at org.jsoup.nodes.Element.outerHtmlTail(Element.java:1506)
	at org.jsoup.nodes.Node$OuterHtmlVisitor.tail(Node.java:749)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
	at org.jsoup.nodes.Node.outerHtml(Node.java:606)
	at org.jsoup.nodes.Element.html(Element.java:1529)
	at org.jsoup.nodes.Element.html(Element.java:1520)
	at org.jsoup.nodes.Document.outerHtml(Document.java:213)
	at org.jsoup.nodes.Node.toString(Node.java:635)
	at java.lang.String.valueOf(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at JsoupIssue1544.main(JsoupIssue1544.java:15)
```
To reproduce:
```
Jsoup.parse(new String(Files.readAllBytes(Paths.get("1544.txt"))));
```
[1544.txt](https://github.com/jhy/jsoup/files/6497442/1544.txt)

**Comment by jhy** [comment]
Hmm, I can't get this one to repro. The timeout issue is different to the OOM @krystiangorecki reports. For the reported timeout, on my laptop it completes in 15 seconds (vs 60 second timeout). Will take a look to see if we can pull in the processing speed.

I think the issue @krystiangorecki saw was fixed in afd73606a90909444e1c443b555dae7b71e6a5a0 (assuming you're not on HEAD?)

**Comment by jhy** [comment]
(The testcase is 88 thousand nested <t= tags...)

**Comment by jhy** [comment]
OK, by limiting the queue depth we scan for formatting elements to <= 256, the performance here is significantly improved. From ~ 14 seconds to 355ms on my laptop. More importantly, it's no longer unbounded.
