### ISSUE TITLE
IndexOutOfBoundsException while trying to insert nested paragraphs and links

### ISSUE THREAD

**Issue by kokorins** [jhy/jsoup#1602]
```kotlin
val bareFragment = "<p></p><a></a>"
Document("").parser().parseFragmentInput(bareFragment, Element("p"), "")
```
ends up with 
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.jsoup.parser.HtmlTreeBuilderState$7.inBodyEndTagAdoption(HtmlTreeBuilderState.java:814)
	at org.jsoup.parser.HtmlTreeBuilderState$7.inBodyEndTag(HtmlTreeBuilderState.java:731)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:288)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:149)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:76)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:133)
	at org.jsoup.parser.Parser.parseFragmentInput(Parser.java:53)
```

**Comment by krystiangorecki** [comment]
Reproducible using 1.14.1, but using 1.13.1  I get NPE because `parser()` returns null.
```
String bareFragment = "<p></p><a></a>";
new Document("").parser().parseFragmentInput(bareFragment, new Element("p"), "");

**Comment by jhy** [comment]
Thanks, fixed! Let me know if you find other issues around these parse fragments; there are clearly some edge-case bugs here because there's nothing else on the stack when created this way.
