### ISSUE TITLE
Element.html throws Null Pointer

### ISSUE THREAD

**Issue by thomashcampbell** [jhy/jsoup#1603]
This worked in Version 1.12.1 but is broken in 1.14.1

        **Element element =
                new Element(Tr_Tag);

        element.html("<tr><td colspan='5' class='bold'>Specials</td></tr>");**

now throws

java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.normalName()" because the return value of "org.jsoup.parser.HtmlTreeBuilder.currentElement()" is null

	at org.jsoup.parser.HtmlTreeBuilderState$9.process(HtmlTreeBuilderState.java:984)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:154)
	at org.jsoup.parser.HtmlTreeBuilderState$13.anythingElse(HtmlTreeBuilderState.java:1186)
	at org.jsoup.parser.HtmlTreeBuilderState$13.process(HtmlTreeBuilderState.java:1169)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:149)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:76)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:133)
	at org.jsoup.parser.Parser.parseFragmentInput(Parser.java:53)
	at org.jsoup.nodes.Element.append(Element.java:679)
	at org.jsoup.nodes.Element.html(Element.java:1620)

**Comment by thomashcampbell** [comment]
Checked 1.13.1 and it worked there as well.

**Comment by kokorins** [comment]
One more similar example:
```kotlin
        val bareFragment = """
<table>
<tr><td></td></tr>
</table>
        """.trimIndent()
        Document("").parser().parseFragmentInput(bareFragment, Element("p"), "")
```

output:
```
java.lang.NullPointerException
	at org.jsoup.parser.HtmlTreeBuilderState$9.process(HtmlTreeBuilderState.java:984)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:149)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:76)
	at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:133)
	at org.jsoup.parser.Parser.parseFragmentInput(Parser.java:53)
```

**Comment by jhy** [comment]
Thanks, fixed!

**Comment by thomashcampbell** [comment]
Confirmed in 1.14.2.  Thank you for the quick turnaround!
