### ISSUE TITLE
Compatibility issues with Cronet.

### ISSUE THREAD

**Issue by ag2s20150909** [jhy/jsoup#1604]
when use cronet as URLStreamHandlerFactory
```URL.setURLStreamHandlerFactory(CronetURLStreamHandlerFactory(engine))```
and got the error.
 
https://github.com/jhy/jsoup/issues/1549

```
Caused by: java.lang.IllegalStateException: Use setFixedLengthStreamingMode() or setChunkedStreamingMode() for writing after connect
        at org.chromium.net.urlconnection.CronetBufferedOutputStream.ensureCanWrite(CronetBufferedOutputStream.java:97)
        at org.chromium.net.urlconnection.CronetBufferedOutputStream.write(CronetBufferedOutputStream.java:82)
W/System.err:     at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at org.jsoup.helper.HttpConnection$Response.writePost(HttpConnection.java:1214)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:861)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)```

**Comment by jhy** [comment]
So, how come you're overriding the URL stream handler? The default implementation does not have those methods mandatory and IMV that impl is out of spec. The methods are there as an optional optimization to remove a buffer.

**Comment by ag2s20150909** [comment]
```D/CronetHttpURLConnection: setConnectTimeout is not supported by CronetHttpURLConnection
W/UrlRequestBuilderImpl: It's not necessary to set Accept-Encoding on requests - cronet will do this automatically for you, and setting it yourself has no effect. See https://crbug.com/581399 for details.
    java.lang.Exception
        at org.chromium.net.impl.UrlRequestBuilderImpl.addHeader(UrlRequestBuilderImpl.java:117)
        at org.chromium.net.impl.UrlRequestBuilderImpl.addHeader(UrlRequestBuilderImpl.java:23)
        at org.chromium.net.urlconnection.CronetHttpURLConnection.startRequest(CronetHttpURLConnection.java:295)
        at org.chromium.net.urlconnection.CronetHttpURLConnection.connect(CronetHttpURLConnection.java:81)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:859)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:353)
```

**Comment by jhy** [comment]
@ag2s20150909 I didn't see an answer to my Q. 

As the implementation is out of spec from the core Java URL Handler which jsoup uses, my suggestion would be to not use this alternate handler. If a manufacturer OS is swapping it out behind the scenes (e.g. as Android does with Okio, but is actually compatible), I would suggest filing bugs against them.
