### ISSUE TITLE
Connection refused: connect

### ISSUE THREAD

**Issue by ys2940** [jhy/jsoup#1701]
TLS authentication has been configured  ，An error occurred while I was accessing  https://www.99774008.com:6899
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)

**Comment by jhy** [comment]
I'm not sure why you filed this as a jsoup bug, as from the stack it just looks like a standard network timeout. Check that your network can connect to that host and port. Perhaps try another troubleshooting forum if you can't resolve the error.

**Comment by ys2940** [comment]
Hello Mr. Jonathan, this is not a bug, using https://try.jsoup.org/ test is OK, accessing the page in the browser of the local computer is ok, but in jsoup1.14.3 I don't know how to implement it, very strange problem.&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonathan ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jhy/jsoup] Connection refused: connect (Issue #1701)





 
I'm not sure why you filed this as a jsoup bug, as from the stack it just looks like a standard network timeout. Check that your network can connect to that host and port. Perhaps try another troubleshooting forum if you can't resolve the error.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
