### ISSUE TITLE
UnsupportedOperationException  (UnmodifiableCollection)

### ISSUE THREAD

**Issue by aci9evil** [jhy/jsoup#1710]
E/AndroidRuntime: FATAL EXCEPTION: Thread-128
    Process: com.tw, PID: 20795
    java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.add(Collections.java:1128)
        at org.adblockplus.libadblockplus.android.webview.SharedCookieManager.get(SharedCookieManager.java:120)
        at com.android.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:715)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:859)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:887)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:353)
        at com.tw.backend.MyNetworkService$11.run(MyNetworkService.java:1953)

String userAgent = System.getProperty("http.agent");
document = Jsoup.connect(url)
                                    .userAgent(userAgent)
                                    .newRequest()
                                    .get();
                                    
                                    
Can't understand why that is going on. All works well, but rare this Exception((

**Comment by aci9evil** [comment]
will try dissable coockie on webview...

**Comment by aci9evil** [comment]
CookieManager.setAcceptFileSchemeCookies(false);
not helped((

**Comment by aci9evil** [comment]
implementation('com.squareup.okhttp3:okhttp:4.9.0')
