### ISSUE TITLE
matchesOwn() performance regression in 1.14.1 (due to reversed selector evaluation)

### ISSUE THREAD

**Issue by mszabo-wikia** [jhy/jsoup#1860]
Hello,

After updating a system that used jsoup from version 1.11.3, we observed that it would hang on processing certain inputs.
A thread dump appears to indicate that threads are busy attempting to match a regex pattern against content:
```
"pool-8-thread-4" #36 prio=5 os_prio=0 cpu=955689.78ms elapsed=3178.18s tid=0x00007ff3ac004180 nid=0x39 runnable  [0x00007ff3c6cf9000]
   java.lang.Thread.State: RUNNABLE
	at java.util.regex.Pattern$GroupTail.match(java.base@17.0.4/Pattern.java:4820)
	at java.util.regex.Pattern$BranchConn.match(java.base@17.0.4/Pattern.java:4698)
	at java.util.regex.Pattern$BmpCharProperty.match(java.base@17.0.4/Pattern.java:3955)
	at java.util.regex.Pattern$Branch.match(java.base@17.0.4/Pattern.java:4734)
	at java.util.regex.Pattern$GroupHead.match(java.base@17.0.4/Pattern.java:4789)
	at java.util.regex.Pattern$CharPropertyGreedy.match(java.base@17.0.4/Pattern.java:4290)
	at java.util.regex.Pattern$BmpCharProperty.match(java.base@17.0.4/Pattern.java:3955)
	at java.util.regex.Pattern$CharPropertyGreedy.match(java.base@17.0.4/Pattern.java:4290)
	at java.util.regex.Pattern$Start.match(java.base@17.0.4/Pattern.java:3608)
	at java.util.regex.Matcher.search(java.base@17.0.4/Matcher.java:1728)
	at java.util.regex.Matcher.find(java.base@17.0.4/Matcher.java:745)
	at org.jsoup.select.Evaluator$MatchesOwn.matches(Evaluator.java:807)
	at org.jsoup.select.CombiningEvaluator$And.matches(CombiningEvaluator.java:55)
	at org.jsoup.select.Collector$FirstFinder.head(Collector.java:88)
	at org.jsoup.select.NodeTraversor.filter(NodeTraversor.java:87)
	at org.jsoup.select.Collector$FirstFinder.find(Collector.java:80)
	at org.jsoup.select.Collector.findFirst(Collector.java:65)
	at org.jsoup.select.Selector.selectFirst(Selector.java:165)
	at org.jsoup.nodes.Element.selectFirst(Element.java:447)
	at com.wikia.services.templateclassificationstorage.logic.classification.matchers.NavboxMatcher.matchTitle(NavboxMatcher.java:97)
```
The code in question looks like this:
```java
  private boolean matchTitle(Document document) {
    return document.selectFirst("title:matchesOwn(.+:.*(N|n)avbox.*)") != null;
  }
```

It appears that this may be a side effect of https://github.com/jhy/jsoup/commit/4861505419b35b5373d00840b3f06775ccbf1454, which changed the order of evaluation for `CombiningEvaluator$And`  such that it now evaluates its components in reverse. Effectively, for the above code, this causes a potentially expensive regex to execute against *every* element in the document, whereas previously it would first limit the search set to only `title` elements and only execute the regex against those.

While the change seems intended, I'm creating this issue since this may adversely affect existing applications and may be counterintuitive for an user who would assume that `matchesOwn`/`matchesText` etc apply the element filter before further matching.

Fortunately the workaround is simple for the time being as one can perform the logic themselves via `getElementsByTag` + regex matching rather than using `selectFirst`.

Thanks in advance!

**Comment by jhy** [comment]
Thanks - we could revert the change (so it matches in the query order) if we implement this todo:
https://github.com/jhy/jsoup/commit/4861505419b35b5373d00840b3f06775ccbf1454#diff-3369013218c26c168286f16311a614a5988557e767405b706092a21d673dfdcbR874

Or, introduce some kind of optimizer that sorts the evaluators by an expected cost. That would be more fun, but probably overkill.

**Comment by jhy** [comment]
I added a cost-based optimizer in 32d247d6f4ec66b10c32be2fb6d2f2666c2399bf which addresses this.

**Comment by mszabo-wikia** [comment]
Thank you!
