### ISSUE TITLE
Thread unsafe behavior

### ISSUE THREAD

**Issue by codymikol** [jhy/jsoup#1892]
When trying to parse documents on two different threads an exception is thrown.

I have made a minimal reproduction over here: https://github.com/codymikol/jsoup-thread-unsafe-demo

Here is the exception in question

```
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.LinkedList.getLast(LinkedList.java:261)
	at org.jsoup.parser.TreeBuilder.currentElement(TreeBuilder.java:58)
	at org.jsoup.parser.HtmlTreeBuilder.insertNode(HtmlTreeBuilder.java:209)
	at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:167)
	at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:156)
	at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.java:208)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.HtmlTreeBuilderState$6.anythingElse(HtmlTreeBuilderState.java:240)
	at org.jsoup.parser.HtmlTreeBuilderState$6.process(HtmlTreeBuilderState.java:224)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.HtmlTreeBuilderState$4.anythingElse(HtmlTreeBuilderState.java:162)
	at org.jsoup.parser.HtmlTreeBuilderState$4.process(HtmlTreeBuilderState.java:138)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.HtmlTreeBuilderState$3.process(HtmlTreeBuilderState.java:89)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.HtmlTreeBuilderState$2.anythingElse(HtmlTreeBuilderState.java:63)
	at org.jsoup.parser.HtmlTreeBuilderState$2.process(HtmlTreeBuilderState.java:55)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.HtmlTreeBuilderState$1.process(HtmlTreeBuilderState.java:32)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:84)
	at org.jsoup.parser.TreeBuilder.runParser(TreeBuilder.java:48)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:41)
	at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:37)
	at org.jsoup.parser.Parser.parseInput(Parser.java:30)
	at MainKt$main$2$1$1.invokeSuspend(Main.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.NoSuchElementException
		... 33 more
```

**Comment by codymikol** [comment]
I did share the code, would you accept a PR to document that Parser instances are not thread safe?

**Comment by codymikol** [comment]
Oh. you're fast, nice :smile:

**Comment by Usmanali72038** [comment]
Nice experience

**Comment by codymikol** [comment]
I'm glad you enjoyed it
