### ISSUE TITLE
Website gives 405 error

### ISSUE THREAD

**Issue by brhurley** [jhy/jsoup#1923]
This page works: https://www.machinerytrader.com

This page gives 405: https://www.machinerytrader.com/listings/for-sale/skid-steers/1055

Is there any fix for this?

The code is just this...

Document webPage = Jsoup.connect(getUrl()).userAgent(
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15").get();

I've tried varying the userAgents to no avail.  

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763) ~[spring-boot-3.0.5.jar:3.0.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.0.5.jar:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar:3.0.5]
	at com.ironmarket.crawler.CrawlerApplication.main(CrawlerApplication.java:25) ~[classes/:na]
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=405, URL=[https://www.machinerytrader.com/listings/for-sale/skid-steers/1055]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:889) ~[jsoup-1.15.4.jar:1.15.4]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:828) ~[jsoup-1.15.4.jar:1.15.4]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:365) ~[jsoup-1.15.4.jar:1.15.4]
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:352) ~[jsoup-1.15.4.jar:1.15.4]
	at com.xxxx.crawler.machinerytrader.MachineryTraderCrawler.crawl(MachineryTraderCrawler.java:36) ~[classes/:na]
	at com.xxxx.crawler.service.CrawlerFactory.initCrawler(CrawlerFactory.java:30) ~[classes/:na]
	at com.xxxx.crawler.CrawlerApplication.run(CrawlerApplication.java:41) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[spring-boot-3.0.5.jar:3.0.5]

**Comment by jhy** [comment]
I expect the server (or CloudFlare in-front) is running some anti-bot code fingerprinting, and there are some specific headers or other trust score mechanism that you will need to work out.

Unfortunately without visibility into the specifics of the check, it's hard to guess what the required incantation will be. I had a quick try by adding the various "sec-ch-ua" etc headers to no immediate avail.

I won't treat this as a jsoup bug because AFAICT there's nothing wrong with the request per se. If you find a way to successfully make the request, it would be helpful to add notes here on how.

**Comment by jhy** [comment]
I was able to coax a 200 out of it, but it's not particularly helpful. These headers:

```java
        Connection session = Jsoup.newSession();

        session.header("Referer", "https://www.machinerytrader.com/listings/for-sale/skid-steers/1055");
        session.header("Accept-Language", "en-US,en;q=0.9");
        session.header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7");
        Connection con = session.newRequest().url("https://www.machinerytrader.com/listings/for-sale/skid-steers/1055");
```

But CloudFlare is running a captcha:

```html
   <h1>Pardon Our Interruption</h1>
   <p>As you were browsing something about your browser made us think you were a bot. There are a few reasons this might happen:</p>
   <ul>
    <noscript>
     <li>You've disabled JavaScript in your web browser.</li>
    </noscript>
    <li>You're a power user moving through this website with super-human speed.</li>
    <li>You've disabled cookies in your web browser.</li>
    <li>A third-party browser plugin, such as Ghostery or NoScript, is preventing JavaScript from running. Additional information is available in this <a title="Third party browser plugins that block javascript" href="https://help.distilnetworks.com/hc/en-us/articles/212154438-Third-Party-Browser-Plugins-That-Block-JavaScript" target="_blank">support article</a>.</li>
   </ul><!-- These paragraphs are displayed depending on if an identify or captcha page is returned  -->
   <p id="identify-msg" style="display: none">To regain access, please make sure that cookies and JavaScript are enabled before reloading the page.</p>
   <p id="captcha-msg" style="display: none">After completing the CAPTCHA below, you will immediately regain access to the site again.</p>
   ```

**Comment by jhy** [comment]
As the author of the website doesn't want user-agents such as jsoup accessing the site, I won't look for further ways to access it.

**Comment by brhurley** [comment]
Thanks for the insight on this.   I'll look for ways to enable javascript and cookies with jsoup and anything else to get around the CloudFlare block.

**Comment by jhy** [comment]
Note that jsoup does support cookies, but it does not execute javascript.
