### ISSUE TITLE
:nth-child() not supported ?

### ISSUE THREAD

**Issue by nremond** [jhy/jsoup#197]
Hi,

When I try to use the :nth-child CSS3 selector as in the following example, I got an SelectorParseException.

The test code : 

``` java
    @Test
    public void testNthChild() {
        final String html = ""
                + "  <ul>                                                 "
                + "   <li><a href=\"http://lemonde.fr\">Le Monde</a></li> "
                + "   <li><a href=\"http://letemps.ch\">Le Temps</a></li> "
                + "  </ul>                                                ";
        final Document doc = Jsoup.parseBodyFragment(html);
        doc.select("ul li:nth-child(1)");
    }
```

the exception : 

```
org.jsoup.select.Selector$SelectorParseException: Could not parse query 'li:nth-child(1)': unexpected token at ':nth-child(1)'
    at org.jsoup.select.QueryParser.findElements(QueryParser.java:150)
    at org.jsoup.select.QueryParser.parse(QueryParser.java:71)
    at org.jsoup.select.QueryParser.parse(QueryParser.java:37)
    at org.jsoup.select.QueryParser.combinator(QueryParser.java:91)
    at org.jsoup.select.QueryParser.parse(QueryParser.java:69)
    at org.jsoup.select.QueryParser.parse(QueryParser.java:37)
    at org.jsoup.select.Selector.<init>(Selector.java:66)
    at org.jsoup.select.Selector.select(Selector.java:79)
    at org.jsoup.nodes.Element.select(Element.java:255)
    at JSoupTest.testNthChild(JSoupTest.java:41)
```

Am I doing anything wrong ?

Thanks for your help,
Nicolas

**Comment by jhy** [comment]
Implemented sometime back
