### ISSUE TITLE
Threadsafety issue in `org.jsoup.nodes.Entities`

### ISSUE THREAD

**Issue by owengray-google** [jhy/jsoup#2042]
We have seen some hung processes when using our (Google's) [dackka](https://cs.android.com/androidx/platform/tools/dokka-devsite-plugin/+/master:src/main/java/com/google/devsite/DevsitePlugin.kt), built on Jetbrains' [dokka](https://github.com/Kotlin/dokka), using jsoup.

I believe the underlying issue we're running into is [in `org.jsoup.nodes.Entities`, where](https://github.com/jhy/jsoup/blob/7d46675bef8cf12397466b8a67599a792fa92b06/src/main/java/org/jsoup/nodes/Entities.java#L29):  
`private static final HashMap<String, String> multipoints = new HashMap<>(); // name -> multiple character references`  
is `static` but is not threadsafe, and that this issue would be fixed by using `ConcurrentHashMap` there.

&nbsp;
&nbsp;
&nbsp;

For reference, the relevant thread dump excerpts:

> I think the dackka process was probably

`4556 org.jetbrains.dokka.MainKt /buildbot/dist_dirs/aosp-androidx-main-linux-androidx/11066813/dackkaArgs-docs-public.json -loggingLevel WARN -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant`
> The full stacktrace for that process is pretty long but I notice that most threads have a stacktrace that looks like this:

```
"DefaultDispatcher-worker-1" #28 daemon prio=5 os_prio=0 cpu=243.46ms elapsed=3478.27s tid=0x00007f99a09cc450 nid=0x122d in Object.wait()  [0x00007f986edeb000]
   java.lang.Thread.State: RUNNABLE
	at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt$parseHtmlEncodedWithNormalisedSpaces$1.invoke(parseWithNormalisedSpaces.kt:25)
	- waiting on the Class initialization monitor for org.jsoup.nodes.Entities
	at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt$parseHtmlEncodedWithNormalisedSpaces$1.invoke(parseWithNormalisedSpaces.kt)
	at org.intellij.markdown.lexer.Compat.forEachCodePoint(Compat.kt:14)
	at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt.parseHtmlEncodedWithNormalisedSpaces(parseWithNormalisedSpaces.kt:19)
	at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt.parseWithNormalisedSpaces(parseWithNormalisedSpaces.kt:49)
	at org.jetbrains.dokka.base.parsers.factories.DocTagsFromIElementFactory.getInstance(DocTagsFromIElementFactory.kt:46)
	at org.jetbrains.dokka.base.parsers.factories.DocTagsFromIElementFactory.getInstance$default(DocTagsFromIElementFactory.kt:16)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.textHandler(MarkdownParser.kt:243)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:391)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren(MarkdownParser.kt:408)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:407)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.defaultHandler(MarkdownParser.kt:355)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:398)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren(MarkdownParser.kt:408)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:407)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.markdownFileHandler(MarkdownParser.kt:201)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode(MarkdownParser.kt:392)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.visitNode$default(MarkdownParser.kt:358)
	at org.jetbrains.dokka.base.parsers.MarkdownParser.parseStringToDocNode(MarkdownParser.kt:40)
	at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion$parseFromKDocTag$1.invoke(MarkdownParser.kt:514)
	at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion.parseFromKDocTag(MarkdownParser.kt:526)
	at org.jetbrains.dokka.base.parsers.MarkdownParser$Companion.parseFromKDocTag$default(MarkdownParser.kt:508)
	at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.getDocumentation(DefaultDescriptorToDocumentableTranslator.kt:1029)
	at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.resolveDescriptorData(DefaultDescriptorToDocumentableTranslator.kt:904)
	at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor.access$resolveDescriptorData(DefaultDescriptorToDocumentableTranslator.kt:135)
	at org.jetbrains.dokka.base.translators.descriptors.DokkaDescriptorVisitor$resolveClassDescriptionData$2.invokeSuspend(DefaultDescriptorToDocumentableTranslator.kt:939)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
> and I notice one thread whose stack looks like this:

```
"DefaultDispatcher-worker-15" #42 daemon prio=5 os_prio=0 cpu=697.27ms elapsed=3478.23s tid=0x00007f9824023400 nid=0x123b in Object.wait()  [0x00007f986d6f0000]
   java.lang.Thread.State: RUNNABLE
	at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:416)
	- waiting on the Class initialization monitor for org.jsoup.nodes.Entities$EscapeMode
	at org.jsoup.nodes.Document.<init>(Document.java:26)
	at org.jsoup.nodes.Document.createShell(Document.java:52)
	at org.jsoup.parser.Parser.parseBodyFragment(Parser.java:218)
	at org.jsoup.Jsoup.parseBodyFragment(Jsoup.java:241)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser$Parse.invoke(JavadocParser.kt:465)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser.convertJavadocElements(JavadocParser.kt:474)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser.convertJavadocElements$default(JavadocParser.kt:471)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser.getDescription(JavadocParser.kt:207)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser.parseDocComment$base(JavadocParser.kt:59)
	at org.jetbrains.dokka.base.translators.psi.parsers.JavadocParser.parseDocumentation(JavadocParser.kt:52)
	at org.jetbrains.dokka.base.translators.psi.DefaultPsiToDocumentableTranslator$DokkaPsiParser$parseClasslike$2.invokeSuspend(DefaultPsiToDocumentableTranslator.kt:243)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by owengray-google** [comment]
Note: there could be other similar `static`-but-not-threadsafe issues, this just appears to be the one we have run into. I believe some lint tools have lint against this case; I don't know if manual inspection of the codebase for it is viable.

**Comment by owengray-google** [comment]
However, given that we observe what looks like a deadlock, the problem might not be the `HashMap` (which usually just gets corrupted from concurrent access), but something else.

There was a related bug in the class involving the initializers, https://github.com/jhy/jsoup/issues/1910.  
The fix to that was released in 1.6.1, and we are seeing this bug in 1.6.1.

Our exception looks similar to [this bug in a different library](https://github.com/jOOQ/jOOQ/issues/11200#issue-781523407), given `	- waiting on the Class initialization monitor for org.jsoup.nodes.Entities$EscapeMode`, and the issue being related to static initializers (` private static void load` is a static initializer).  

I think this suggests that https://github.com/jhy/jsoup/commit/b6f652cef6dca7904d8ea0b971e4fc3812530015 might have just converted the `NullPointerException` case to a deadlock somehow?

**Comment by owengray-google** [comment]
Actually, upon inspection while our dependency has updated to 1.6.1, we haven't updated to the version of the dependency that has 1.6.1.  
I will see if taking up  that fix fixes our issue.

**Comment by jhy** [comment]
For some context - the static hashmap `multipoints` in [Entities](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Entities.java) is write once, read many. I don't immediately see how using ConcurrentHashMap would help anything here. We don't want to concurrently write to it. When the class is initalized, the EscapeMode enums in their static initialization will serially load the entities from packed data into the hashmap. Thereafter there are no writes to the map, and so multi-thread reading is safe.

As far as I can see I don't believe this is related to #1910 as that was a straight single-thread path to a null pointer.

And I can't see a deadlock path in those stack traces (or in the code). Do you have more thread dumps that shows two threads are waiting on each other?

My expectation for this is that if you have many threads running, and then they all suddenly want to load Entities for the first time, there will be a race to lock the static initializer, and one thread will win. It will quickly (like, a few millis) parse the entities data and write to the hashmap, then unlock and the other threads will resume. The times you have in that trace look awful!

Is something else causing the Entities to be evicted from permgen? Does this lock happen at startup or after running for some time? How many concurrent threads are there?

**Comment by jhy** [comment]
That they are waiting on different initializers is interesting and I wonder if there's a path there?

```
at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:416)
- waiting on the Class initialization monitor for org.jsoup.nodes.Entities$EscapeMode
at org.jsoup.nodes.Document.<init>(Document.java:26)
```

```
at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt$parseHtmlEncodedWithNormalisedSpaces$1.invoke(parseWithNormalisedSpaces.kt:25)
- waiting on the Class initialization monitor for org.jsoup.nodes.Entities
at org.jetbrains.dokka.base.translators.ParseWithNormalisedSpacesKt$parseHtmlEncodedWithNormalisedSpaces$1.invoke(parseWithNormalisedSpaces.kt)
```

**Comment by jhy** [comment]
@owengray-google do you have any further info for this? Without a way to repro I haven't been able to make any progress here.

**Comment by owengray-google** [comment]
Androidx is open-source, but this is a low-probability flake, less than 1%.
We recently tried to force the version we use to 1.16.2, but that landed shortly before thanksgiving when no builds ran, and we want to wait a bit to make sure this is still happening.

**Comment by jhy** [comment]
Thanks for the update. It's interesting. I have been able to craft a kind-of repro by adding a Thread.sleep(2000) as a static initializer in each of Entities and OutputSettings. And then a runner which spawns a few threads which run a Entities.escape and a Document.parseBodyFragment. It will threadlock in a similar manner to those threads above.

However, I find that only happens when I rollback the changes for #1910. If I leave them in (the lazy init), even with adding extra sleeps about the place, I can't get it to threadlock like that.

I can take a pass on refactoring to further decouple OutputSettings and Entities during initialization. Would you be able to evaluate a snapshot / branch version of jsoup with a tentative fix?

**Comment by jhy** [comment]
> We recently tried to force the version we use to 1.16.2, but that landed shortly before thanksgiving when no builds ran, and

Can you confirm what version you are running that produced those dumps?

> at org.jsoup.parser.Parser.parseBodyFragment(Parser.java:218)

That line must be from a version older than 1.16.2, because I added some lines for namespaces at the top of [Parser](https://github.com/jhy/jsoup/blame/master/src/main/java/org/jsoup/parser/Parser.java) which pushes it to line 227.

Is it possible that you are running a version earlier than 1.16.1? Prior to the OutputSettings lazy load being enabled?

**Comment by jhy** [comment]
Ping @owengray-google, are you able to check that?

**Comment by owengray-google** [comment]
Sorry about that. It turns out that our upstream dependency is jarjaring the old version of jsoup, so we're trying to upgrade to a newer version of it, but the version with a newer jsoup also includes an upgrade to the Kotlin K2 compiler that has a lot of breaking changes, so it's taking a bit.

**Comment by jhy** [comment]
Hi @owengray-google - just checking in. Is this still occurring with current versions of jsoup for you?

**Comment by jhy** [comment]
@owengray-google could you explain the status please. I don't want to drop it if there's still an underlying issue. Great if the updated version means that it no longer manifests.

**Comment by jhy** [comment]
That's great, thanks for confirming. And no trouble.

**Comment by jhy** [comment]
With b731fd772bb4c313e6582e1bd3e6298cd8ccec19 I have further decoupled OutputSettings and Entities.
