### ISSUE TITLE
JSoup 1.17.1: java.lang.NullPointerException: Cannot invoke "org.jsoup.parser.Token.startPos()" because "token" is null

### ISSUE THREAD

**Issue by henricook** [jhy/jsoup#2068]
Hi all,

I've been unable to upgrade to 1.17.1 from 1.16.2

From a check of the source it looks like there's insufficient checking around whether `currentToken` is not-null? Or I'm lacking context on what `currentToken` is.

I think the issue was introduced here: https://github.com/jhy/jsoup/pull/2056/files

If you add this test to `PositionTest.java` it recreates the issue, this is how I parse a document in 1.16.2:

```java
    // Based on tracksClosingHeadingTags
    @Test void tracksTagsFromDocumentShell() {
        String html = "<h1>One</h1><h2>Two</h2><h10>Ten</h10>";
        Document shellDoc = Document.createShell("");

        // Should not throw a NullPointerException (currently: throws a NullPointerException)
        List<Node> nodes = TrackingHtmlParser.parseFragmentInput(html, shellDoc.body(), shellDoc.baseUri());

        /// ... Sorry I'm a Scala guy not a Java guy so casting to Element etc here would be a lot for me to lookup
    }
```

Error:

`java.lang.NullPointerException: Cannot invoke "org.jsoup.parser.Token.startPos()" because "token" is null`

Stack:

```
java.lang.NullPointerException: Cannot invoke "org.jsoup.parser.Token.startPos()" because "token" is null
  at org.jsoup.parser.TreeBuilder.trackNodePosition(TreeBuilder.java:253)
  at org.jsoup.parser.TreeBuilder.onNodeInserted(TreeBuilder.java:238)
  at org.jsoup.parser.TreeBuilder.push(TreeBuilder.java:143)
  at org.jsoup.parser.HtmlTreeBuilder.parseFragment(HtmlTreeBuilder.java:138)
  at org.jsoup.parser.Parser.parseFragmentInput(Parser.java:61)
```

**Comment by jhy** [comment]
Fixed! Sorry about that, and thanks for the clear report.

**Comment by henricook** [comment]
Awesome, thanks for responding so fast @jhy !
