### ISSUE TITLE
jsoup 1.6.3 breaks functionality with Android

### ISSUE THREAD

**Issue by fschwaiger** [jhy/jsoup#211]
Hello,

I tried to upgrade from 1.6.2 to 1.6.3 of the lib in my Android app project but now experience force closes. The problem seems to be the loading procedure of properties from file, which is unavailable on Android.
The following is the stack trace, not complete as it was retraced with proguard mapping. So some method calls could not be identified correctly and choices were given.

Caused by: java.lang.ExceptionInInitializerError
at org.jsoup.nodes.Document$OutputSettings.<init>(Unknown Source)
at org.jsoup.nodes.Document.<init>(Unknown Source)
at org.jsoup.parser.TreeBuilder.initialiseParse(Unknown Source)
at org.jsoup.parser.TreeBuilder.parse(Unknown Source)
                                        process
at org.jsoup.parser.HtmlTreeBuilder.parse(Unknown Source)
                                            process
                                            process
                                            transition
                                            state
                                            framesetOk
                                            maybeSetBaseUri
                                            insert
                                            insert
                                            insert
                                            insert
                                            isElementInQueue
                                            popStackToClose
                                            insertOnStackAfter
                                            replaceInQueue
                                            inSpecificScope
                                            inSpecificScope
                                            inScope
                                            insertInFosterParent
at org.jsoup.parser.Parser.parseInput(Unknown Source)
                                   isTrackErrors
at org.jsoup.helper.DataUtil.load(Unknown Source)
                                     parseByteData
                                     readToByteBuffer
                                     getCharsetFromContentType
at org.jsoup.helper.HttpConnection$Response.parse(Unknown Source)
at org.jsoup.helper.HttpConnection.url(Unknown Source)
                                           timeout
                                           get

... my code calling "Document = Jsoup.connect(service).timeout(timeout).get();"

Caused by: java.lang.ExceptionInInitializerError
at org.jsoup.nodes.Entities$EscapeMode.<clinit>(Unknown Source)
... 24 more
Caused by: java.lang.NullPointerException
at java.util.Properties.load(Properties.java:264)
at org.jsoup.nodes.Entities.loadEntities(Unknown Source)
                                    access$200
at org.jsoup.nodes.Entities.<clinit>(Unknown Source)
... 25 more

Hope this helps.

Regards,
Florian

**Comment by amal** [comment]
There is no need for such wide rule as `-keep public class org.jsoup.**`

Simple
`-keepnames class org.jsoup.nodes.Entities`
is enough.

Jsoup tries to load _.properties_ files from the package of this class, but it couldn't if its package is changed, because ProGuard doesn't respectively change package of properties files. So we should simply keep name for this class.

**Comment by dasebasto** [comment]
I confirm that amal's solution works. Thanks.
