### ISSUE TITLE
There's null issue in org.jsoup.select.Elements#set

### ISSUE THREAD

**Issue by MicyToy** [jhy/jsoup#2212]
the new `org.jsoup.select.Elements#set(int, Element)` method since 1.17.1 has an issue.

this call `old.replaceWith(element)` method, and this method calls `parentNode.replaceChild(this, in)`. in the `replaceChild` method, out's parentNode is removed  `out.parentNode = null;`. this may cause an null issue.

eg: a parent node has 5 child elements, if I replace the 3rd element twice, like first replace 1 and 3, and then replace 5 and 3, then will throw an exception.
```
org.jsoup.helper.ValidationException: Object must not be null
	at org.jsoup.nodes.Node.replaceWith(Node.java:512)
	at org.jsoup.select.Elements.set(Elements.java:703)
	at org.jsoup.select.Elements.set(Elements.java:30)
```

you also can test it with `Collections.shuffle()`

**Comment by MicyToy** [comment]
I've pushed a test case for this.
[Issue 2212](https://github.com/MicyToy/jsoup/tree/issue/issue_2212)

**Comment by jhy** [comment]
Thanks, I added support for that case. 

When calling `set` or other methods which re-parent nodes, the outgoing node is detached from the DOM by removing its parent. So now the replaceChild method tests to see if the outgoing node has a parent, and if not will fall back to trying to use the incoming node's parent. If that doesn't have a parent either, the flow will necessarily still abandon.
