### ISSUE TITLE
java.lang.NoClassDefFoundError: org.jsoup.internal.StringUtil$$ExternalSyntheticLambda5

### ISSUE THREAD

**Issue by iqtoon** [jhy/jsoup#2240]
java.lang.NoClassDefFoundError: org.jsoup.internal.StringUtil$$ExternalSyntheticLambda5
**This problem occurred with the last three versions of Android Studio. Is there a solution? Thank you.**

--------

  FATAL EXCEPTION: main
                                                                                                    Process: com.example.myapplication, PID: 16501
                                                                                                    java.lang.NoClassDefFoundError: org.jsoup.internal.StringUtil$$ExternalSyntheticLambda5
                                                                                                    	at org.jsoup.internal.StringUtil.<clinit>(StringUtil.java:341)
                                                                                                    	at org.jsoup.helper.UrlBuilder.build(UrlBuilder.java:44)
                                                                                                    	at org.jsoup.helper.HttpConnection$Base.url(HttpConnection.java:437)
                                                                                                    	at org.jsoup.helper.HttpConnection$Request.url(HttpConnection.java:594)
                                                                                                    	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:144)
                                                                                                    	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:84)
                                                                                                    	at org.jsoup.Jsoup.connect(Jsoup.java:93)
                                                                                                    	at com.example.myapplication.MainActivity.getData(MainActivity.kt:18)
                                                                                                    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:14)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:6877)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)

**Comment by jhy** [comment]
Hi,

Did you follow the note in the README?

Android support
When used in Android projects, [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) with the [NIO specification](https://developer.android.com/studio/write/java11-nio-support-table) should be enabled to support Java 8+ features.

And/or, what Android API version are you targeting? Per the [Java 11 Android compat notes](https://developer.android.com/studio/write/java11-default-support-table), API level 33 will also include those without explicitly adding the desugaring config.
