### ISSUE TITLE
Simple connection error - IllegalCharsetNameExcpetion

### ISSUE THREAD

**Issue by morro91** [jhy/jsoup#335]
With the simple line: (WebsiteUtility.java:19)

		        Document doc = Jsoup.connect("http://www.1wow.com.au/game-of-thrones-season-2-118264-336020.html").get();

I get the following exception
		        java.nio.charset.IllegalCharsetNameException

While I can use the code to make it work:

		        URL yahoo = new URL("http://www.1wow.com.au/game-of-thrones-season-2-118264-336020.html");
		        URLConnection yc = yahoo.openConnection();
		        BufferedReader in = new BufferedReader(new InputStreamReader(
		                yc.getInputStream(), "UTF-8"));
		        
		        String inputLine;
		        StringBuilder a = new StringBuilder();
		        while ((inputLine = in.readLine()) != null)
		            a.append(inputLine);
		        in.close();
	
		        return a.toString();

I would like this to be fixed. The error does seem to do with the "UTF-8" encoding.

The full stack trace for the error above is:

		        Exception in thread "main" java.nio.charset.IllegalCharsetNameException: UTF-8,text/html
		        at java.nio.charset.Charset.checkName(Charset.java:320)
		        at java.nio.charset.Charset.lookup2(Charset.java:496)
		        at java.nio.charset.Charset.lookup(Charset.java:475)
		        at java.nio.charset.Charset.isSupported(Charset.java:517)
		        at org.jsoup.helper.DataUtil.getCharsetFromContentType(DataUtil.java:154)
		        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:465)
		        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:446)
		        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410)
		        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164)
		        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:153)
		        at utilities.WebsiteUtility.getUrlSource(WebsiteUtility.java:19)
		        at sales.Site.<init>(Site.java:18)
		        at sales.sites.wow.<init>(wow.java:13)
		        at sales.Play.processProducts(Play.java:114)
		        at sales.Play.main(Play.java:47)

Thanks.

**Comment by jhy** [comment]
Sorry I can't repro this as the URL 404s. However I did change jsoup to fallback to UTF-8 on unsupported character sets, so I expect this condition would pass now.
