### ISSUE TITLE
Exception "Unexpected end of ZLIB input stream" when response is redirected

### ISSUE THREAD

**Issue by nirzohar** [jhy/jsoup#443]
I get exception Unexpected end of ZLIB input stream when try to send GET request to a URL, and the URL is redirected.

For example: 

---

```
    Connection conn = Jsoup.connect("http://www.bizportal.co.il/article/390749")
        .timeout(Constants.HTTP_CONN_TIMEOUT)
        .userAgent(Constants.USER_AGENT)
        .followRedirects(false);
    Response response = conn.execute();
```

---

Stack trace:

---

java.io.EOFException: Unexpected end of ZLIB input stream
    at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:142)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:483)
    at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
    at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)

---

**Comment by rktamplayo** [comment]
Are there any updates regarding this issue? I am also getting the same error, even when the website's content type is utf-8.

**Comment by jhy** [comment]
Do you have a code snippet I can use to repro? Incl URL and any other variables. A Charles or other proxy log would be useful also.

**Comment by jhy** [comment]
(Closing out old, dormant bugs. If you are still impacted by this, please reopen & vote.)
