### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by AlexMercier** [jhy/jsoup#494]
when i'm using jsoup 1.8.1 for android i got outofmemory exception when execute request 2-3 times.
```java
//the code for 1.8.1 version
Document doc = Jsoup.connect(url) 
                     .cookies(getCookie()) 
                     .maxBodySize(0) // page size around 6Mb (also i try 2mb page and memory issue also) 
                     .get();
```
returned  html contains too many elements and application is crashed after 2-3 passing of get url.
I think this is memory leak bug because with old jsoup version  1.5.2 all works fine without outofmemory!!! (i found this solution in stackoverflow dot com).
please fix this error, i wanna use newest version of jsoup.
if you need get page dump here https://dropbox.com/s/dyhb3z52lohdwbx/dump_page.html?dl=1

**Comment by AlexMercier** [comment]
STACK_TRACE=java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
	at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:146)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:498)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at ru.gemobile.toramp.utils.Parser.parseMyNewSerials(Parser.java:216)
	at ru.gemobile.toramp.fragments.FragmentNewSeries$11.run(FragmentNewSeries.java:391)
	at java.lang.Thread.run(Thread.java:856)

**Comment by jhy** [comment]
That stack indicates that it's running out of memory trying to allocate a buffer to read contents into. It doesn't indicate a leak. If you could answer the other parts of my question we might be able to get further.

**Comment by jhy** [comment]
Please reopen if you can answer those Qs and indicate a leak.
