### ISSUE TITLE
DataUtil doesn't check if <meta charset> is a supported charset before continuing

### ISSUE THREAD

**Issue by BalusC** [jhy/jsoup#508]
E.g. http://chortle.ccsu.edu/java5/index.html having a `<meta charset="iso-8">` therefore causes `UnsupportedCharsetException`.

```
 java.nio.charset.UnsupportedCharsetException: iso-8
	at java.nio.charset.Charset.forName(Charset.java:531)
	at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:98)
	at org.jsoup.helper.DataUtil.load(DataUtil.java:49)
	at org.jsoup.Jsoup.parse(Jsoup.java:118)
	...
```

Reproducer:
```java
byte[] content = "<html><head><meta charset=iso-8></head><body></body></html>".getBytes("UTF-8");
Document document = Jsoup.parse(new ByteArrayInputStream(content), null, "http://example.com");
```

Solution: rewrite `DataUtil#parseByteData()` from
```java
                if (meta.hasAttr("http-equiv")) {
                    foundCharset = getCharsetFromContentType(meta.attr("content"));
                    if (foundCharset == null && meta.hasAttr("charset")) {
                        try {
                            if (Charset.isSupported(meta.attr("charset"))) {
                                foundCharset = meta.attr("charset");
                            }
                        } catch (IllegalCharsetNameException e) {
                            foundCharset = null;
                        }
                    }
                } else {
                    foundCharset = meta.attr("charset");
                }
```
to
```java
                if (meta.hasAttr("http-equiv")) {
                    foundCharset = getCharsetFromContentType(meta.attr("content"));
                }
                if (foundCharset == null && meta.hasAttr("charset")) {
                    try {
                        if (Charset.isSupported(meta.attr("charset"))) {
                            foundCharset = meta.attr("charset");
                        }
                    } catch (IllegalCharsetNameException e) {
                        foundCharset = null;
                    }
                }
```

**Comment by jhy** [comment]
Thanks both; merged.
