### ISSUE TITLE
a  problem

### ISSUE THREAD

**Issue by hetao8613** [jhy/jsoup#573]
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readUInt(Unknown Source)
	at java.util.zip.GZIPInputStream.readTrailer(Unknown Source)
	at java.util.zip.GZIPInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:154)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:560)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)
	at cn.rsvp.collector.site.BaseUnitCollector.extractUrls(BaseUnitCollector.java:116)
	at cn.rsvp.collector.site.TongChengCollector.generateSeedUrlsList(TongChengCollector.java:36)
	at cn.rsvp.collector.site.BaseUnitCollector.execute(BaseUnitCollector.java:60)
	at cn.rsvp.collector.site.TongChengCollector.main(TongChengCollector.java:185)

**Comment by jhy** [comment]
Do you have more details, like what site and a code snippet? Does it work in other browsers? Looks like a corrupt gzip output from the service.
