### ISSUE TITLE
StringIndexOutOfBoundsException calling Document.select(cssQuery)

### ISSUE THREAD

**Issue by liamsharp** [jhy/jsoup#635]
Can be reproduced by the following 2 lines: 

```
Document doc = Jsoup.parse("");
doc.select("section > a[href=\"");
```

Which gives:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1911)
at org.jsoup.select.Evaluator$AttributeKeyPair.<init>(Evaluator.java:284)
at org.jsoup.select.Evaluator$AttributeWithValue.<init>(Evaluator.java:152)
at org.jsoup.select.QueryParser.byAttribute(QueryParser.java:236)
at org.jsoup.select.QueryParser.findElements(QueryParser.java:150)
at org.jsoup.select.QueryParser.parse(QueryParser.java:65)
at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
at org.jsoup.select.QueryParser.combinator(QueryParser.java:81)
at org.jsoup.select.QueryParser.parse(QueryParser.java:61)
at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
at org.jsoup.select.Selector.<init>(Selector.java:83)
at org.jsoup.select.Selector.select(Selector.java:105)
at org.jsoup.nodes.Element.select(Element.java:258)
```

I guess this should throw Selector.SelectorParseException?

**Comment by jhy** [comment]
I checked and it's now returning a IllegalArgumentException - string must not be empty.

All the other validations in there are the same (IllegalArgumentException) mostly. Could move them but probably not very useful.

**Comment by mahmooddagga** [comment]
@jhy  thanks very much for this great library .... waiting next version 1.10.2 , i hope it will be soon
