### ISSUE TITLE
:selection not supported?

### ISSUE THREAD

**Issue by simonered** [jhy/jsoup#668]
Hi,

I'm trying to parse *material-design-lite.css* and I get a **SelectorParseException**. Is `:selection` not supported?

     org.jsoup.select.Selector$SelectorParseException: Could not parse query ':selection': unexpected       token at ':selection'
	at org.jsoup.select.QueryParser.findElements(QueryParser.java:196) ~[jsoup-1.8.3.jar:na]
	at org.jsoup.select.QueryParser.parse(QueryParser.java:53) ~[jsoup-1.8.3.jar:na]
	at org.jsoup.select.QueryParser.parse(QueryParser.java:39) ~[jsoup-1.8.3.jar:na]
	at org.jsoup.select.Selector.<init>(Selector.java:83) ~[jsoup-1.8.3.jar:na]
	at org.jsoup.select.Selector.select(Selector.java:105) ~[jsoup-1.8.3.jar:na]
	at org.jsoup.nodes.Element.select(Element.java:273) ~[jsoup-1.8.3.jar:na]
    [...]

**Comment by jhy** [comment]
You don't put CSS into `select`, you put CSS queries. I.e. see the examples.
