### ISSUE TITLE
java heap space

### ISSUE THREAD

**Issue by vahid-01** [jhy/jsoup#694]
I use jsoup for parsing html and get java heap space error with this code. my heap space is 8G.
I think you can improve memory usage for this kind of documents.
version jsoup 1.8.2.

Document document ..... 
String htmlContent = document.html();
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at org.jsoup.nodes.Node.indent(Node.java:581)
	at org.jsoup.nodes.Element.outerHtmlHead(Element.java:1122)
	at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:679)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
	at org.jsoup.nodes.Node.outerHtml(Node.java:559)
	at org.jsoup.nodes.Element.html(Element.java:1164)
	at org.jsoup.nodes.Element.html(Element.java:1158)

I attached file.

[lawdotic.html.zip](https://github.com/jhy/jsoup/files/193136/lawdotic.html.zip)

**Comment by jonathanlermitage** [comment]
Hi,
I think it can't be considered as a bug since your HTML file is a non-sens ;) (a ton of DL openings, then another ton of DL endings, seriously... ^^).
Sincerely,

**Comment by vahid-01** [comment]
this HTML is real world document. you can see document from this link : 
http://law.dotic.ir/AIPLaw/lawview.do?sectionId=1661296&reqCode=lawView&lawId=102596&stateNo=0&allNode=1&lawViewLST.param.withInterpretation=true&requestedSectionId=1661296
this source file is about 500KB. How is can consume 8GB heap space.
document has 80000 line and if each node use 4 byte for pointer, it use 32 KB ram for DOM tree.

**Comment by jonathanlermitage** [comment]
The Java model can't use 4 bytes only to store a single node, there's plenty of data to store in order to maintain business logic.
I guess that an optimization (to handle insane DOM trees) would introduce complex changes in the `org.jsoup.nodes.Node` class.

Maybe you could consider using an alternative, like PhantomJS or SlimerJS. They're able to handle your file.

**Comment by jhy** [comment]
(That doc crashed Chrome on my 8GB Mac Pro, btw)

You're running out of memory during HTML serialization. That just simply appends to a StringBuilder. The doc isn't using 8GB of heap, but you're running out of memory creating an array large enough to hold the output.

It's possible you'd have enough if you allocated a string builder large enough to handle the full output directly (because it avoids the array recreations for expansion).

There's possibilities to reduce the size of the Node / Element objects, but it's never going to be 4 bytes.

Will close this as not directly actionable.
