### ISSUE TITLE
does not open files with unicode characters correctly

### ISSUE THREAD

**Issue by emmanueltouzery** [jhy/jsoup#715]
I was [trying](https://github.com/iamthechad/javadoc2dash/issues/8) to use an application using `jsoup` to parse the `javadoc` from the javaslang library.
That library [has a class named λ](http://static.javadoc.io/io.javaslang/javaslang/2.0.2/javaslang/%CE%BB.html).
Because of that in the javadoc there is a link to a file named %CE%BB in the link. But on-disk the file name is λ. Unfortunately that confuses jsoup and it fails parsing the HTML:

```
Caused by: java.io.FileNotFoundException: /home/emmanuel/Downloads/javaslang-javadoc/javaslang/%CE%BB.html (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.jsoup.helper.DataUtil.readFileToByteBuffer(DataUtil.java:179)
	at org.jsoup.helper.DataUtil.load(DataUtil.java:46)
	at org.jsoup.Jsoup.parse(Jsoup.java:103)
	at com.megatome.j2d.support.JavadocSupport.loadAndFindLinks(JavadocSupport.java:192)
	... 5 more
```

**Comment by jhy** [comment]
Have you got a test case? Because DataUtil and Jsoup.parse both take File objects, not links or anything. So I think the error is in how you're making the File object in your JavadocSupport file.

**Comment by emmanueltouzery** [comment]
You are correct. I was under the impression that that application parsing the HTML was relying on `jsoup` to recursively follow links but that was not the case.
I've now modified the application so that when it reads a link text through `Element.attr("href")`, it decodes it too: `java.netURLDecoder.decode(e.attr("href"), "UTF-8")`, and that fixes the issue. Sorry for the false alarm and thank you for the feedback!
