### ISSUE TITLE
IndexOutOfBoundsException  in DataUtil.parseByteData

### ISSUE THREAD

**Issue by recastrodiaz** [jhy/jsoup#727]
First of all, I'd like to congratulate @jhy and contributors for this amazing library! It's really super useful! 

Without further ado, I've found a small bug when the server responds with an empty body and using the XmlParserFactory. I can provide a Pull Request if needed.

**Repro code**
```JAVA 
Response response = Jsoup
					.connect("http://www.kansascity.com/entertainment/columnists/timothy_finn/index.xml")
					.parser(new DocumentScraperService.XmlParserFactory())//
					.ignoreContentType(true) //
					.execute();

response.parse(); // Boom
```

**Stacktrace**
``` LOG
http://www.kansascity.com/entertainment/columnists/timothy_finn/index.xml - java.lang.IndexOutOfBoundsException -
java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454)
        at org.jsoup.nodes.Node.childNode(Node.java:195)
        at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:116)
        at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:652)
``` 

**Patch in DataUtil line 116:** https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/helper/DataUtil.java#L116

from:
``` JAVA
// look for <?xml encoding='ISO-8859-1'?>
            if (foundCharset == null && doc.childNode(0) instanceof XmlDeclaration) {
```
to:
``` JAVA
// look for <?xml encoding='ISO-8859-1'?>
            if (foundCharset == null && doc.childNodeSize() > 0 && doc.childNode(0) instanceof XmlDeclaration) {
```

**Comment by jhy** [comment]
Thanks!
