### ISSUE TITLE
exception on W3CDOM fromJSoup() in case attribute with invalid characters

### ISSUE THREAD

**Issue by dbenesj** [jhy/jsoup#738]
In case of invalid HTML file that include attribute with single double-quote, there is an exception while trying to create W3C DOM.
One of the example is following page: [http://www.zive.sk/](http://www.zive.sk/)
There is following problematic HTML code:
```html
<a onclick="gaTrack('hp-zive', 'box-top-spravy', '2');" class="link" mobilmania" href="http://mobilmania.azet.sk/clanok/116656/pravda-o-extremne-lacnych-telefonoch-odkial-sa-beru">
```
Problematic attribute is: _mobilmania"_

Stack trace is following:
```java
Exception in thread "main" org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createAttribute(CoreDocumentImpl.java:611)
	at com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttribute(ElementImpl.java:498)
	at org.jsoup.helper.W3CDom$W3CBuilder.copyAttributes(W3CDom.java:124)
	at org.jsoup.helper.W3CDom$W3CBuilder.head(W3CDom.java:92)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
	at org.jsoup.helper.W3CDom.convert(W3CDom.java:66)
	at org.jsoup.helper.W3CDom.fromJsoup(W3CDom.java:46)
	at JSoupException.main(JSoupException.java:14)
```

Here is example code that raise exception:
```java
import org.jsoup.Jsoup;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Document;

public class JSoupException {
    public static void main(String[] args) throws Exception {
        Document doc = Jsoup.connect("http://www.zive.sk/")
                .userAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36")
                .get();
        W3CDom w3cDom = new W3CDom();
        org.w3c.dom.Document w3cDoc = w3cDom.fromJsoup(doc);
        System.out.println(w3cDoc.toString());
    }
}
```

How could I create valid W3C DOM from this page?
I'm looking for more general solution than modifying just this exact problem one I found it.

**Comment by dbenesj** [comment]
same problem as #721 
ignoring invalid attribute names seems as good idea

**Comment by jhy** [comment]
Thanks!
