### ISSUE TITLE
OutputSettings is not threadsafe, throws ISE in canEncode when shared

### ISSUE THREAD

**Issue by wlk** [jhy/jsoup#740]
I stumbled on this problem:
```
java.lang.IllegalStateException: Current state = CODING_END, new state = CODING
    at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:992)
    at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:904)
    at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:985)
    at org.jsoup.nodes.Entities.escape(Entities.java:154)
    at org.jsoup.nodes.TextNode.outerHtmlHead(TextNode.java:100)
    at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:678)
    at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
    at org.jsoup.nodes.Node.outerHtml(Node.java:551)
    at org.jsoup.nodes.Element.html(Element.java:1203)
    at org.jsoup.nodes.Element.html(Element.java:1197)
    at org.jsoup.Jsoup.clean(Jsoup.java:235)
```

Issue is most likely appearing under high load (?), this doesn't happen every time I run the cleaning for the same string
```
Jsoup.clean(input, domainName, myWhiteList, new OutputSettings().indentAmount(0).prettyPrint(false))
```

**Comment by wlk** [comment]
also similar stack stack trace with most likely the same root cause:
```
java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:992)
	at java.nio.charset.CharsetEncoder.flush(CharsetEncoder.java:675)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:804)
	at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:910)
	at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:985)
	at org.jsoup.nodes.Entities.escape(Entities.java:154)
	at org.jsoup.nodes.TextNode.outerHtmlHead(TextNode.java:100)
	at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:678)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
	at org.jsoup.nodes.Node.outerHtml(Node.java:551)
	at org.jsoup.nodes.Element.html(Element.java:1203)
	at org.jsoup.nodes.Element.html(Element.java:1197)
	at org.jsoup.Jsoup.clean(Jsoup.java:235)
```

**Comment by jhy** [comment]
Have you got a test case that can replicate? What's your environment?

It sounds like it might be a race condition (how else would load impact it?), but the encoder is created afresh in each OutputSettings (which is new for a Document).

Unless you're reusing an OutputSetting in a multithreaded environment? That could be the cause. If that's the case and the cause we may need to change how the encoder is creating in OutputSettings.

**Comment by wlk** [comment]
Yes, in fact I was sharing `OutputSettings` between threads, I didn't find any indication that it's not thread safe, the name suggests that those are static configurations, it's of course more obvious after reading the code.
Thanks for the help, I think the issue can be closed

**Comment by jhy** [comment]
Thanks - we can treat this as a bug that OutputSettings is not threadsafe / thread shareable.

**Comment by jhy** [comment]
Can you give me a fuller code sample and your environment? I.e. in your sample there's no actual reuse of OutputSettings. I haven't been able to replicate it with a contrived brute force test case.

**Comment by wlk** [comment]
I think we might have misunderstood each other at some point :)
In this scenario:
```
Jsoup.clean(input, domainName, myWhiteList, new OutputSettings().indentAmount(0).prettyPrint(false))
```
There are no problems.


But after your previous comment I reviewed my code and there was a different use case:

```
class IndexEndpoint {
  val defaultOutputSettings = new OutputSettings().indentAmount(0).prettyPrint(false)
  val domainName = "http://localhost"

  def index(input: String) = {
    val cleandedInput = Jsoup.clean(input, domainName, myWhiteList, defaultOutputSettings)
    respond(cleandedInput)
  }
}
```

In this scenario I have created a `defaultOutputSettings` which I was sharing by multiple threads which were processing HTTP requests inside `index` method. And if there were enough parallel requests the race condition happening which resulted in the exception. A single instance of class `IndexEndpoint` was used by multiple threads

**Comment by jhy** [comment]
I've committed what should be a fix. But I wasn't able to repro when encoding with hundreds of parallel  threads sharing the same output settings and text that was hitting the canencode / encode methods that was having problems.

If you can test against HEAD that would be helpful.

**Comment by wlk** [comment]
Sorry for late reply: I think this fixes the issue, I'm no longer seeing the problem.
