### ISSUE TITLE
SSL Exception 

### ISSUE THREAD

**Issue by SocialRaceMedia** [jhy/jsoup#761]
I receive this SSL Exception
(javax.net.ssl.SSLException) javax.net.ssl.SSLException: Received fatal alert: internal_error

when attempting to retrieve this page
https://www.cannabisbusinessexecutive.com/2016/09/netherlands-near-legalizing-regulated-marijuana-cultivation/

here is the call I am making

Document haDocument = Jsoup.connect(articleUrl)
             .validateTLSCertificates(false)
             .followRedirects(true)
             .userAgent(myUserAgent)
             .referrer(myReferrer)
             .ignoreHttpErrors(true)
             .timeout(20000)
             .get();

Im using 
Jsoup version 1.9.2
Java JDK version 1.8_102   in the NetBeans IDE

**Comment by Tyf0x** [comment]
Same issue using Coldfusion 11, java 1.8.0_25, jsoup 1.9.2.

```
javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1104)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl.connect(HttpsURLConnectionOldImpl.java:142)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:563)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:540)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:227)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at [...]
```

**Comment by jhy** [comment]
You're missing the current Java crypto libraries. See [here](https://stackoverflow.com/a/38264878/153184)
