### ISSUE TITLE
ConcurrentModificationException caused by Node.removeAttr()

### ISSUE THREAD

**Issue by charlesmadere** [jhy/jsoup#779]
```
java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:411)
    at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:422)
    at org.jsoup.nodes.Attributes.removeIgnoreCase(Attributes.java:122)
    at org.jsoup.nodes.Node.removeAttr(Node.java:128)
```

Specifically, the loop in [`Attributes.removeIgnoreCase()`](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Attributes.java#L122) has a problem: if a remove does occur, this crash will always follow.

This appears to be a new issue in `1.10.1`, as it never occurred for me in `1.9.2`. Which makes sense, the `1.9.2` behavior was different: [`Attributes.java`](https://github.com/jhy/jsoup/blob/5dc4c487d42705f60ff6e5b95d03c71a3326d6cd/src/main/java/org/jsoup/nodes/Attributes.java#L81).

**Comment by charlesmadere** [comment]
Sorry, this is a duplicate of #759
