### ISSUE TITLE
Cannot set a request body for HTTP method GET

### ISSUE THREAD

**Issue by HexValid** [jhy/jsoup#872]
Hi,

I get this error when I exec this code:

```
Jsoup.connect(URL_API)
                .cookies(this.cookies)
                .ignoreContentType(true)
                .header("Accept", "application/json")
                .header("Content-Type", "application/json; charset=UTF-8")
                .header("Connection", "keep-alive")
                .header("X-CSRF-Token", csrf2)
                .header("X-Requested-With", "XMLHttpRequest")
                .maxBodySize(255)
                .requestBody(json)
                .method(Connection.Method.POST)
                .post();
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot set a request body for HTTP method GET
	at org.jsoup.helper.Validate.isFalse(Validate.java:64)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:639)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:676)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:628)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:260)
	at org.jsoup.helper.HttpConnection.post(HttpConnection.java:255)
```

Why this error, even though I set to `method(Connection.Method.POST)` ?

Thanks

**Comment by Siedlerchr** [comment]
I encountered the same error and I am still wondering

**Comment by Siedlerchr** [comment]
After the req.data.Clear you have to do call `req.requestData(null) `
