### ISSUE TITLE
Receiving java.lang.IllegalArgumentException: protocol = http host = null With Some Pages

### ISSUE THREAD

**Issue by adxBRudolph** [jhy/jsoup#932]
The home page of the domain "minecraft-server-list.com" is successfully fetched but the child pages in the domain fail with the error "java.lang.IllegalArgumentException: protocol = http host = null" on the <Connection>.get() call.

Some pages tested:

     http://minecraft-server-list.com/server/108375
     http://minecraft-server-list.com/server/306576/vote
     https://minecraft-server-list.com/sort/Vanilla

This is occurring in release 1.10.3

**Comment by mccxj** [comment]
@adxBRudolph could you show the full stacktrace and the testcase?

**Comment by adxBRudolph** [comment]
Found using Jsoup 1.10.1, 1.10.2 and 1.10.3 running on both Java 7 & 8

Code snippet in Fetcher class that fetches the page at the provided URL. The User Agent header is set and a timeout is set in the Jsoup connection. The exception is thrown by the "**connect.get()**" call. Example URLs in the origin post.

```
Connection connect = Jsoup.connect(asciiUrl)​.userAgent(_doc.getUserAgent()).timeout(timeout.intValue()).validateTLSCertificates(false);
Document document = connect.get();​

```

Exception caught in code with Java 7 and Jsoup 1.10.3 (removed part of stack trace that is irrelevant - shown as ":")

```
java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:170)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:927)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:652)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:679)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:629)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:261)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:250)
	at Fetcher.process(Fetcher.java:318)
	at ws.Service.executeSequence(Service.java:137)
	at ws.Service.process(Service.java:89)
	at HttpHandler.channelRead(HttpHandler.java:173)
	              :
	              : 
	at java.lang.Thread.run(Thread.java:745)

```
Exception caught in code with Java 8 and Jsoup 1.10.3 (removed part of stack trace that is irrelevant - shown as ":")

```
java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1099)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:652)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:679)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:629)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:261)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:250)
	at Fetcher.process(Fetcher.java:318)
	at ws.Service.executeSequence(Service.java:137)
	at ws.Service.process(Service.java:89)
	at HttpHandler.channelRead(HttpHandler.java:173)
	              :
	              : 
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mccxj** [comment]
jsoup use pure HttpURLConnection for http request. maybe you should check URL#getHost() == null? 
```java
req.url().getHost() == null?
```
req is the first param of method HttpConnection$Response.execute.

**Comment by jhy** [comment]
Can you provide a test case that demonstrates this? I.e. a Junit test we can cut&paste and see the problem. Haven't been able to replicate. And did you check per @mccxj suggestion?

**Comment by tux-mind** [comment]
I've encountered this same problem.

In the following test, if you comment the Jsoup line OkHttp works fine, except with the last one, which has an empty host, resulting in an exception when building the request. 

```java
@Test
public void illegalArgumentSearch() {
    OkHttpClient client = new OkHttpClient();

    for (String url : new String[]{
            "https://ctt.ec/0fPmC+", "https://clicktotweet.com/0fPmC+",
            "https:%20//thespiritledlife.com/831047284/reporthotmail.php"
    }) {
        try {
            URL u = new URL(url);
            log.info("host = '{}'", u.getHost());
            Jsoup.connect(url).get();
            client.newCall(new Request.Builder().url(u).build()).execute().body().string();
        } catch (Exception e) {
            log.info("Url: {}, Exception: <{}> {}", url, e.getClass(), e.getMessage());
            if (!(e instanceof IOException)) {
                log.error("Stack: ", e);
            }
        }
    }
}
```

Extra bits:

```java
private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(YourTest.class);
```

```groovy
implementation 'com.squareup.okhttp3:okhttp:3.14.7'
compile 'org.jsoup:jsoup:1.13.1'
```

Thank you for your time and this great project of yours :)
