### ISSUE TITLE
NPE in entity comparison in parse

### ISSUE THREAD

**Issue by AllanWang** [jhy/jsoup#944]
I don't have many details is this is from an outside user, but there seems to be a situation where an NPE can occur when comparing entities

The report: http://crashes.to/s/b20eb2c81a0

The reactiveX errors are from my not catching the error, and everything starts with me parsing Facebook's search page.

**Comment by AllanWang** [comment]
May be [here](https://github.com/jhy/jsoup/blob/master/src/main/java/org/jsoup/nodes/Entities.java#L312)?

Not sure if 

```
final String name = reader.consumeTo('=');
```

may return null

**Comment by jhy** [comment]
I have a feeling this in an Android issue I've seen reported on other projects where on first install of an app, on some devices, Android won't find resources in a jar if they're loaded statically. Entities is loading the entity mapping file statically on startup.

**Comment by AllanWang** [comment]
Are you referring to here?

```Java
private static final HashMap<String, String> multipoints = new HashMap<>(); // name -> multiple character references
```

Would you consider adopting a singleton pattern if that may help with compatibility?

**Comment by AllanWang** [comment]
Bump? I have another NPE [here](http://crashes.to/s/db4f35afc81) and I'm assuming it's a similar issue

**Comment by jhy** [comment]
Looks like a different stack. Can you include the stacks here so we don't have to keep hitting that other site and can find in search etc please.

Entities have changed implementation so I'd recommend bumping to 1.11.1 if the initial stack is because of the entity loading issue. f3035cafbbd8830de75f641920f8e5dbf0070f7c

For the different stack (Attributes.getIgnoreCase:67) - that's been reimplemented since whatever version your stack is. The map impl was refactored. Suggest revving to the current release.

**Comment by AllanWang** [comment]
It is indeed a different stack. Just the NPE lead me to believe the issue is similar. This was on 1.10.3, so I will close this and see if it will reappear. 

Stack for search:

```kotlin
Non-fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap$LinkedHashMapEntry java.util.LinkedHashMap$LinkedHashMapEntry.after' on a null object reference
       at java.util.LinkedHashMap$LinkedHashIterator.(LinkedHashMap.java)
       at java.util.LinkedHashMap$LinkedHashIterator.(LinkedHashMap.java)
       at java.util.LinkedHashMap$KeyIterator.(LinkedHashMap.java)
       at java.util.LinkedHashMap$KeyIterator.(LinkedHashMap.java)
       at java.util.LinkedHashMap.newKeyIterator(LinkedHashMap.java:452)
       at java.util.HashMap$KeySet.iterator(HashMap.java:1188)
       at org.jsoup.nodes.Attributes.getIgnoreCase(Attributes.java:67)
       at org.jsoup.nodes.Element.id(Element.java:133)
       at org.jsoup.select.Evaluator$Id.matches(Evaluator.java:91)
       at org.jsoup.select.Collector$Accumulator.head(Collector.java:42)
       at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:31)
       at org.jsoup.select.Collector.collect(Collector.java:24)
       at org.jsoup.nodes.Element.getElementById(Element.java:708)
       at com.pitchedapps.frost.web.SearchWebView$setupWebview$1.apply(SearchWebView.kt:61)
       at com.pitchedapps.frost.web.SearchWebView$setupWebview$1.apply(SearchWebView.kt:28)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
       at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
       at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:140)
       at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:165)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by jhy** [comment]
Please open an issue if you get a recurrence on the current release.
