### ISSUE TITLE
ssl request failed

### ISSUE THREAD

**Issue by hhhaiai** [jhy/jsoup#958]
java code
```Java
Jsoup.connect("https://api.macvendors.com/60-d9-a0-da-f8-e7").get();
```
Error

```Shell
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:652)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:629)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:261)
	at org.jsoup.helper.HttpConnection.post(HttpConnection.java:256)
	at cn.mac.Mac.getManufacturerByMac(Mac.java:31)
	at cn.mac.Mac.main(Mac.java:20)
```

**Comment by krystiangorecki** [comment]
That's not Jsoup's fault. This one fails as well:
```import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;

public class JsoupIssue958 {

	public static void main(String[] args) throws IOException {
		URL website = new URL("https://api.macvendors.com/60-d9-a0-da-f8-e7");
		URLConnection connection = website.openConnection();
		InputStream inputStream = connection.getInputStream();
		// (...)
	}

}

**Comment by jhy** [comment]
This is because your Java installation doesn't support current encryption settings. You can add the right jars, or upgrade to Java 9. Some more details [here](https://stackoverflow.com/a/38264878/153184)

**Comment by softashu** [comment]
Hi @jhy is it not resolve in java 8

**Comment by jhy** [comment]
For Java 6, 7, 8, you need to install the crypto jars I linked above.

**Comment by softashu** [comment]
after install  the jars i am getting 


main, WRITE: TLSv1.2 Change Cipher Spec, length = 1
main, handling exception: java.net.SocketException: Connection reset by peer: socket write error
%% Invalidated:  [Session-4, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384]
main, SEND TLSv1.2 ALERT:  fatal, description = unexpected_message
main, WRITE: TLSv1.2 Alert, length = 2
main, Exception sending alert: java.net.SocketException: Connection reset by peer: socket write error
main, called closeSocket()
Connection reset by peer: socket write error

**Comment by jhy** [comment]
Please see https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html

And I saw other useful docs when Googling "SEND TLSv1.2 ALERT: fatal, description = unexpected_message"

Just for clarity, Jsoup is just using the JRE's OpenUrlConnection. It doesn't implement SSL/TLS, the JRE does. The path to solving is to configuring your JRE correctly. 

When you find the solution please mention it here to help others :)
