### ISSUE TITLE
version 1.11.1 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by vmariox** [jhy/jsoup#966]
version 1.10.3 no problem
version 1.11.1 java.lang.StackOverflowError
Example URL：
http://szshb.nxszs.gov.cn/
http://www.lnfsfda.gov.cn/
http://www.beihai.gov.cn/
http://www.fsepb.gov.cn/
http://www.bhem.gov.cn

**Comment by jhy** [comment]
Specifically the trace looks like

```
java.lang.StackOverflowError
	at org.jsoup.helper.Validate.isFalse(Validate.java:53)
	at org.jsoup.parser.Token$Tag.name(Token.java:134)
	at org.jsoup.parser.HtmlTreeBuilder.insert(HtmlTreeBuilder.java:209)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:305)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
	at org.jsoup.parser.HtmlTreeBuilderState$15.anythingElse(HtmlTreeBuilderState.java:1207)
	at org.jsoup.parser.HtmlTreeBuilderState$15.process(HtmlTreeBuilderState.java:1201)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:137)
	at org.jsoup.parser.TreeBuilder.processStartTag(TreeBuilder.java:66)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:707)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
	at org.jsoup.parser.HtmlTreeBuilderState$15.anythingElse(HtmlTreeBuilderState.java:1207)
	at org.jsoup.parser.HtmlTreeBuilderState$15.process(HtmlTreeBuilderState.java:1189)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:137)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:708)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
```

Looks like it's getting stuck trying to handle a bad closing`p` or something?

**Comment by jhy** [comment]
Worklog

The error is somewhere in the `</p>` in this block:

```html
<span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-family:宋体;color:#000000;"><span style="font-size:14px;line-height:21px;"> </span><p style="text-align:center;margin-top:0pt;margin-bottom:0pt;" class="p0"><span style="font-size:14px;">PM</span><sub>2.5</sub></p>
</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span>
```

**Comment by jhy** [comment]
Thanks for the bug report. This is fixed now. Sorry for the problem.
