### ISSUE TITLE
Infinite timeout not working anymore

### ISSUE THREAD

**Issue by lukasschlueter** [jhy/jsoup#968]
Hi,

### Description
After upgrading to the latest version (previously had 1.10.2) my program started to immediately time out on every request:
```
java.net.SocketTimeoutException: Read timeout
    at org.jsoup.internal.ConstrainableInputStream.read(ConstrainableInputStream.java:58)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at org.jsoup.internal.ConstrainableInputStream.readToByteBuffer(ConstrainableInputStream.java:87)
    at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:169)
    at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:103)
    at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:832)
```

### Source of Error
I did some investigation and noticed that I was setting the timeout to 0 to disable it completely. I had a look at the code and came across this section in ConstrainableInputStream:
```
    public int read(byte[] b, int off, int len) throws IOException {
        if (expired())
            throw new SocketTimeoutException("Read timeout");
    ...

    private boolean expired() {
        if (timeout == -1)
            return false;
    ...
```
This code effectively treats a timeout of -1 as infinite timeout and was introduced by https://github.com/jhy/jsoup/commit/a63fcab33707b7b466fbbf4ce4e7e63d787ba23e and contains the bug.
However, the documentation for timeout states:
`A timeout of zero is treated as an infinite timeout.`
When trying to set the timeout to -1, jsoup throws an IllegalArgumentException:
```
Exception in thread "main" java.lang.IllegalArgumentException: Timeout milliseconds must be 0 (infinite) or greater
    at org.jsoup.helper.Validate.isTrue(Validate.java:45)
    at org.jsoup.helper.HttpConnection$Request.timeout(HttpConnection.java:581)
    at org.jsoup.helper.HttpConnection$Request.timeout(HttpConnection.java:537)
    at org.jsoup.helper.HttpConnection.timeout(HttpConnection.java:156)
```

### Solution
Change ContrainableInputStream#expired to check for 0 instead of -1.
While -1 is very commonly used for infinite timeouts, allowing a timeout of 0 would not have much use as it could never succeed.

Greetings

**Comment by jhy** [comment]
Thanks for the report, and sorry for the issue! Fixed now.
