### ISSUE TITLE
NPE: NULL href in <a> causes protocol analysis in Cleaner to crash.

### ISSUE THREAD

**Issue by jjfiv** [jhy/jsoup#973]
Tiny reproduction from trying to clean some older HTML files.
EDIT: I am on latest (1.11.1 via Maven)

    Jsoup.clean("<a href>clean-NPE</a>", Whitelist.basic())

This throws a NPE when the Cleaner tries to validate it has a reasonable protocol. I think this is because HREF is actually present in the tag, but its value is ``null``.

Stack trace:

    Exception in thread "main" java.lang.NullPointerException
	at org.jsoup.internal.Normalizer.lowerCase(Normalizer.java:11)
	at org.jsoup.safety.Whitelist.testValidProtocol(Whitelist.java:547)
	at org.jsoup.safety.Whitelist.isSafeAttribute(Whitelist.java:507)
	at org.jsoup.safety.Cleaner.createSafeElement(Cleaner.java:154)
	at org.jsoup.safety.Cleaner.access$100(Cleaner.java:35)
	at org.jsoup.safety.Cleaner$CleaningVisitor.head(Cleaner.java:111)
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:45)
	at org.jsoup.safety.Cleaner.copySafeNodes(Cleaner.java:142)
	at org.jsoup.safety.Cleaner.clean(Cleaner.java:58)
	at org.jsoup.Jsoup.clean(Jsoup.java:200)
	at org.jsoup.Jsoup.clean(Jsoup.java:215)

Workaround: remove HREF attr (since I only care about the text in my application)

    Whitelist.basic().removeAttributes("a", "href")

**Comment by jhy** [comment]
Thanks! Fixed.
