### ISSUE TITLE
IOException: Mark has been invalidated (Android 6)

### ISSUE THREAD

**Issue by pkk0** [jhy/jsoup#990]
Hi, I have issue with this library on Android ~<=23. 

I'm trying to parse the page using:
`Document d = Jsoup.connect("").get();`

Unfortunately, this causes an error: 
```
 java.io.IOException: Mark has been invalidated.
   at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
   at org.jsoup.internal.ConstrainableInputStream.reset(ConstrainableInputStream.java:103)
   at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:105)
   at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:832)
   at org.jsoup.helper.HttpConnection.get(HttpConnection.java:289)
```

Similar problem: https://stackoverflow.com/questions/47733379/java-io-ioexception-mark-has-been-invalidated-when-parsing-website-with-jsoup

I hope you can fix it in the next release.

**Comment by jhy** [comment]
What's the URL so I can replicate?

**Comment by criss721** [comment]
check this out : https://github.com/jhy/jsoup/issues/992

**Comment by jhy** [comment]
Thanks for reporting and the detail (also on #992)
